### PR TITLE
Improve unit tests 3

### PR DESCRIPTION
**Pull request by service-paradis**
Improve many components unit tests

Also add snapshots validation

### CODE REVIEW

**Comment by jtommy** [comment]
First all thanks a lot!!
Please check it because there are two errors

**Comment by service-paradis** [comment]
Yes, I'm working on it right now.
Date are a real pleasure to work with lol

**Comment by service-paradis** [comment]
@jtommy Fixed!

**Comment by service-paradis** [comment]
@jtommy 
I'm getting CircleCI Timeout really often...

**Comment by service-paradis** [comment]
@jtommy 
Finally got it! `TableColumn` tests was taking an eternity on CircleCI. I modified it to be lightweight.

Sorry for the spam you must have received from this PR!!

**Comment by jtommy** [comment]
Wonderful!!

**Pull request merged**
