### PR TITLE
test: add UT for Autocomplete, Checkbox and CheckboxButton

### PR DESCRIPTION
**Pull request by 14nrv**
## coverage:
* Autocomplete: 91.9%
* Checkbox: 100%
* CheckboxButton: 83.3%
> global: 40.3%

### CODE REVIEW

**Comment by jtommy** [comment]
@anteriovieira Could you take a look ?

**Comment by 14nrv** [comment]
@jtommy Yes I think, because it's much easier to write unit tests with this package, it provide some very useful helpers / shortcuts

**Comment by jtommy** [comment]
We have updated vue-test-utils version, so you should fix conflicts.
Anyway I'm not convinced about the need to add 'mwangaben-vthelpers'.

**Comment by 14nrv** [comment]
@anteriovieira done

**Comment by jtommy** [comment]
@14nrv Thanks!

**Pull request merged**
