### PR TITLE
Auto complete with category

### PR DESCRIPTION
**Pull request by quadra-diffusion**
Fixes #

## Proposed Changes

- Present data by category in result of autocomplete
-
-

### CODE REVIEW

**Comment by quadra-diffusion** [comment]
Hello problem with the timeout of the CI, please re-launch it thks

**Comment by quadra-diffusion** [comment]
I make a lot of cheat with my repository so i close it to represent later

**Comment by jtommy** [comment]
@quadra-diffusion Thanks but I don't think it's the correct way because I don't like make assumptions about data prop

**Comment by quadra-diffusion** [comment]
@jtommy ok i understand, i try to search a new solution. I'v pushed a new pull request about the same thing but i have a problem with snapshot, so do i commit new snapshot ?

**Pull request closed without merging**
