### PR TITLE
Suggestion: row groups

### PR DESCRIPTION
**Pull request by c0bra**
# Suggestion: Row groups

Ability to group rows by a certain column and provide visual "group headers".  Here's a screenshot:

image

Our business has a case where we need row groups and we'd like to stick with Buefy components if possible. This PR just represents a basic test to see if it could work, and it seems to. There would need to be more work to make sure it performs as expected with sorting, filtering, responsiveness, etc. I'm just opening this for feedback.

Thanks!

### CODE REVIEW

**Comment by jtommy** [comment]
It's a great feature!! @c0bra

**Comment by c0bra** [comment]
- [ ] Allow deep property bindings
- [ ] Extract row groups from regular sorting
- [ ] Fix colspan
- [ ] Make sure row groups work with filtering

**Comment by service-paradis** [comment]
Nice work @c0bra 💯 
Will mark this as a draft while you're still working on it!

**Comment by wesdevpro** [comment]
@c0bra what is the status of this PR?

**Comment by c0bra** [comment]
@wesdevpro our business pivoted away from Vue so I was not able to pursue working on it.

**Comment by wesdevpro** [comment]
> @wesdevpro our business pivoted away from Vue so I was not able to pursue working on it.

Could you fill me in on what this draft was left at and what the next steps were to complete this PR?

**Pull request closed without merging**
