### PR TITLE
Search Filter Addition

### LINKED ISSUE #555: Searchable Table
Hello, How to add search box in table? Is it possible?

Thank you.

### LINKED ISSUE #888: Search Table: Feature Request
### Overview of the problem

**Buefy** version: Latest
**Vuejs** version: 2.9.6
**OS/Browser**: GNU/Linux - Mozilla Firefox

### Description

Hi. when I was working in my company, I added a new feature to Buefy. Because I needed it. Our data was very large. We needed to search in the table. So, I did small modifications for Buefy tables.

All those modifications are very basic to use. There are three props for this feature. These are;

**search-table**: This prop is giving boolean value.

**search-location**: This prop is giving string value. The values must be `is-pulled-right` or `is-pulled-left`. The default value is `is-pulled-right`

**search-place-holder**: This prop is giving string value. If the developer wants to show placeholder. The default value is `Search...`

I added a gif to understand what I'm saying. If this feature seems useful, I can open pull request to dev branch.

### Animated Gif

search-buefy

### PR DESCRIPTION
**Pull request by robertmarney**
Fixes #888 
Fixes #555 

## Proposed Changes

Adds a searchable modifier to table initialization which will create a column specific search filter within the table header.

Original Author is @tonystonee

### CODE REVIEW

**Comment by quadra-diffusion** [comment]
@robertmarney Hi, do you want to continue on this pull request ? or can i take it for finish it ? best regards

**Comment by quadra-diffusion** [comment]
@robertmarney Hello, how are you ? I add tests for increase the coverage code ratio but i can't push my commit on your branche. Can you give me the permission please ?

**Comment by quadra-diffusion** [comment]
@robertmarney Hello, can you finish the job with the test that i send you ?

**Comment by robertmarney** [comment]
#

**Pull request closed without merging**
