### PR TITLE
Add aria label to close button in b-tag

### PR DESCRIPTION
**Pull request by yxngl**
## Proposed Changes
Add `aria-label` to the close button in b-tag for better accessibility.

### CODE REVIEW

**Comment by service-paradis** [comment]
I think this should be a prop (`ariaCloseLabel`) like in other components. Would be better for localization.

**Comment by yxngl** [comment]
Good point

**Comment by jtommy** [comment]
You are free to open a new PR ;)

**Comment by yxngl** [comment]
Just realized message has the same prop, but it does not have a default. Should I leave it empty as well?

**Comment by jtommy** [comment]
In message component there isn't a default value

**Comment by gntlman-bstrd** [comment]
is there some progress regarding that issue? 
Accessibility is still a problem for tags with a close button. :/

**Comment by jtommy** [comment]
@gntlman-bstrd There is already a prop to set it in the last version

**Pull request merged**
