### PR TITLE
BREAKING: Set defaultTrapFocus to true

### PR DESCRIPTION
**Pull request by service-paradis**
For the next breaking release

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
Can you explain little bit about that?
Coz really dont get why it needed here, for what is that trap Focus?

Only for broken browser's which are can't hook unfocus or what?

**Comment by service-paradis** [comment]
It helps keep the focus into an open modal.
Without this directive, if you open a modal and keep using the `TAB` key, the browser will give focus to external element.
It is mostly for better accessibility

**Comment by afwn90cj93201nixr2e1re** [comment]
Get you, one more, on dropdown in modal, there's no div's, which prevent parent scrolling.


Also, maybe we should just write some wrapper for buefy?
https://github.com/theKashey/react-focus-lock

**Comment by service-paradis** [comment]
The directive already exists to trap focus on element. The props have been added to various components.
This PR is just to set the default behavior to true.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://codepen.io/arina11/pen/QWWrjGx?editors=1010

Fix that too. Coz i don't wanna.
GIF

**Comment by service-paradis** [comment]
It is not related to this PR...
If there is an issue for it, I will try to take a look at it when I will have time for this.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/buefy/buefy/blob/dev/src/components/modal/Modal.vue#L14 there is the fix.

One more question, why it's breaking change? I don't see anything broken with `true`.

**Comment by service-paradis** [comment]
Because, right now, the focus is not trapped inside those component when they are opened. By setting this to `true`, it will change this default behavior.

**Comment by afwn90cj93201nixr2e1re** [comment]
I know, but what's is breaking in that?

**Comment by service-paradis** [comment]
Nothing will really break, but it is a breaking change since a default behavior is changed.

Actually, someone that do not want the focus to be trapped is not using `trap-focus`. If this gets merged, they will need to add a prop to keep their current behavior.

**Comment by francoism90** [comment]
Just a heads up, someone can already define this by default using [Contructor Options](https://buefy.org/documentation/constructor-options): `defaultTrapFocus: true`

**Pull request merged**
