### PR TITLE
new lazy modifier for b-input

### PR DESCRIPTION
**Pull request by FragsterAt**
this is needed for barcode scanners etc.
ugly fix for https://github.com/buefy/buefy/issues/640

### CODE REVIEW

**Comment by jtommy** [comment]
@FragsterAt lazy modifier is the sugar syntax of `:value="myvalue @change="onchange"` but about b-input is `:value="myvalue @change.native="($event) => onchange($event.target.value)"`.
Maybe I could emit a change event like input but `lazy` prop is unnecessary

**Comment by FragsterAt** [comment]
@jtommy unfortunately parent component updates value on('input'), even it has v-model.lazy modifier :(
my workaround is to add attribute to avoid emiting 'input' event from child component.

**Comment by FragsterAt** [comment]
@jtommy 
> b-input is :value="myvalue @change.native="($event) => onchange($event.target.value)".

`<b-input :value="value " @change.native="($event) => value = $event.target.value"`
it works, but it is much less clear, than 
`<b-input v-model="value" lazy>`

**Comment by jtommy** [comment]
Yes but i want to follow vue standard

**Pull request closed without merging**
