### PR TITLE
Tooltip on table header fix

### PR DESCRIPTION
**Pull request by shelru**
Before:
image
image

After:
image

### CODE REVIEW

**Comment by shelru** [comment]
Related to https://github.com/buefy/buefy/issues/1330

**Comment by jtommy** [comment]
It's only a workaround. I want to improve tooltip component in order to append it in the body

**Comment by shelru** [comment]
Again? Seriously? This hotfix is not directed at tooltip, but on all elements 
 in the table headers. You can read about overflow-x, but seem's you never get it, again.

**Comment by shelru** [comment]
image
Your corrections, improvments and reviews sometimes take more than a year. Isn't it better to fix now, and when will new tooltip revert commit(If even then you don't understand the problem with overflow-x)?

**Comment by jtommy** [comment]
You could make a PR improving tooltip component if you want.
Could you provide me an example without tooltip that this PR fix?

**Comment by shelru** [comment]
As I said earlier, in a similar way you are only slowing down the development of the project on the background of others. We must approve more PR  asap and check more issue's, nothing is ideal initially, in development process we can review errors to correct and modify components, making them more convenient and customizable.

> You could make a PR improving tooltip component if you want.

I still do not see any reasons for PR, as I wrote above, some PR is not considered for a long time.

> Could you provide me an example without tooltip that this PR fix?

Make some custom slot and on hove show custom tooltip(not component from buefy), and you gonna get same issue on low resolutions.

**Comment by jtommy** [comment]
I already told you, please respect us.
We love contributions, for example datepicker was born from a PR, but they needs a review to check the Buefy philosophy respect and to ensure the proper operation.
Buefy is a free open source project and we can dedicate a part of our free time.

Anyway i might be in wrong and so I asked you to let me know a reason to accept this PR.

**Pull request closed without merging**
