### PR TITLE
fix day on select date

### PR DESCRIPTION
**Pull request by BlackMix**
looks doc.. has bug on select: 2 = 1, 3 = 2 etc
+ 1 in day fix it

### CODE REVIEW

**Comment by jtommy** [comment]
@BlackMix Why? In the Date object docs:
getDate() - Get the day as a number (1-31)

**Comment by BlackMix** [comment]
@jtommy looks on your doc and click any day

**Comment by jtommy** [comment]
@BlackMix What's your timezone ?

**Comment by BlackMix** [comment]
@jtommy https://cdn.discordapp.com/attachments/410021276212658186/468173197238468639/bug.mp4

BRT america/recife

**Comment by jtommy** [comment]
@BlackMix I cannot reproduce the issue. 
Are you trying in the current develop branch or in last version (current online docs) ?

**Comment by BlackMix** [comment]
current online doc and version 0.6.6

**Comment by BlackMix** [comment]
so let me close it and install dev version lol

**Pull request closed without merging**
