### PR TITLE
Fix single spaces in templates.

### LINKED ISSUE #1927: Replacing extra new lines to nothing instead single space on compilation step.
https://github.com/buefy/buefy/issues/1703

Close when it's gonna be fixed.

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**
Fixes #1927, #1703

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
But it doesnt fix useless `\n              ` which caused by 
изображение

if we gonna replace spaces to tabs it also gonna create `\n\t\t\t\t....`

so, there no fixes for that, instead of creating shadow copy of files for compiler only, or using compiler options:
https://github.com/vuejs/vue/issues/3934#issuecomment-319310032
https://github.com/vuejs/vue/issues/3934#issuecomment-442163264

I can try to make it if you gonna create regular expression for handling this stuff(new line and spaces).

**Comment by jtommy** [comment]
@afwn90cj93201nixr2e1re if i didn't see bad using `withespace` the compiler doesn't check `preserveWhitespace` attrs

**Comment by afwn90cj93201nixr2e1re** [comment]
Yes, that's why it's disabled in commit.

**Comment by jtommy** [comment]
Ok but default value is undefined, you might omit it, don't you ?

**Comment by afwn90cj93201nixr2e1re** [comment]
If we gonna use whitespace option(by default it's preserve) this spaces gonna be saved in template
изображение
https://github.com/buefy/buefy/blob/dev/src/components/table/Table.vue#L92

Oh, i but in docs it's 'preserve' by default.

**Comment by jtommy** [comment]
I mean whitespaceOption

**Comment by afwn90cj93201nixr2e1re** [comment]
Can't find it in https://github.com/vuejs/vue/search?q=whitespaceOption.whitespace&unscoped_q=whitespaceOption.whitespace, are you talking about vue plugin or vue?

**Comment by jtommy** [comment]
https://github.com/vuejs/vue/blob/3dcd85b82693765b13e866132bcaa318ef086fe5/src/compiler/parser/index.js#L99

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/buefy/buefy/pull/1944#issuecomment-549157590
what about TS class and docs?
Are you sure that this is undefined by default?
Im really not sure.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/vuejs/vue/blob/730a10f771cf722fd28994b0501ad7b04534882a/packages/vue-template-compiler/types/index.d.ts#L10

https://github.com/vuejs/vue/blob/4c98f9de39e18703ec3dbd05b596a1bbc3d0c8e3/flow/compiler.js#L10

one more

**Comment by afwn90cj93201nixr2e1re** [comment]
Seem's like i add it for future support(when you gonna merge project to 2.6.x).
Coz it's really doesnt exisist in 2.5.x
https://github.com/vuejs/vue/blob/v2.5.22/flow/compiler.js#L9

**Comment by jtommy** [comment]
@afwn90cj93201nixr2e1re reading the TS in the future we'll able to use only 'preserve' or 'condense'

**Comment by afwn90cj93201nixr2e1re** [comment]
In 2.6.x preserveWhitespace is not deleted, i think they 'r not going to delete it, coz it's deprecated since 2016.

https://github.com/vuejs/vue/issues/9208#issuecomment-450012518

In TS deprecated coz by default it's enabled, in vue-cli there preserveWhitespace setted to false, it's just notation.
https://github.com/vuejs/vue-cli/commit/1864cef09e186cdf094fca876f8638a8ba1b4adb

**Comment by afwn90cj93201nixr2e1re** [comment]
As you can see it's also supported by vue-cli 4, and vue 3.x.x
https://deploy-preview-4552--vue-cli.netlify.com/migrating-from-v3/#vue-cli-service

**Comment by afwn90cj93201nixr2e1re** [comment]
Oops.

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtimmy any solution?

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtimmy ping?

**Comment by afwn90cj93201nixr2e1re** [comment]
Can you answer? Coz i have another method, if you don't wanna merge this one.

**Comment by jtommy** [comment]
I should read docs because it's an important change

**Comment by afwn90cj93201nixr2e1re** [comment]
I think it's not important at all. Coz it's a framework, so, it's handling spaces in 2-3 cases at all, other spaces should be removed.

**Comment by afwn90cj93201nixr2e1re** [comment]
Any updates?

**Comment by afwn90cj93201nixr2e1re** [comment]
Same as previous.

**Comment by afwn90cj93201nixr2e1re** [comment]
What about this one @jtommy .

**Comment by Tofandel** [comment]
If you want to reopen this
```
const vuePluginConfig = {
    template: {
        isProduction: true,
        compilerOptions: {
            whitespace: 'condensed',
        }
    }
}
```

This is the configuration, it will not cause any issue with the build, I am using this option for all my projects as well

The [doc of rollup](https://rollup-plugin-vue.vuejs.org/options.html#template-compiler) is outdated

**Comment by afwn90cj93201nixr2e1re** [comment]
He don't wanna do it.

**Comment by afwn90cj93201nixr2e1re** [comment]
Just pls stop saying stuff like that without any deep knowledge.
изображение

Read docs about that before saying anything about 'cosmetic' changes, read ton's of issues where it was descrbied by Evan especially.
You shouldn't write code like that: 
```
<span>
  text
</span>
```

It's not right, read vue docs and other stuff which related to compiler parsing, there's shouldn't be any useless spaces (also no useless LF/CRLF (new line symbols)) if they are not needed.

> you know you can make pull requests to fix those issues as well

Boi, ofc i know,

> and it doesn't mean there can't be a new major fixing those and new issues in a few months

Also pls stop saying that, jtommy doesnt making any breakable changes on 0.9.0+ releases coz it's gonna be brekable and that's why we wait for months/years just for getting fixes...

**Comment by jtommy** [comment]
Make a PR if you want

**Comment by Tofandel** [comment]
@afwn90cj93201nixr2e1re Wow you're so rude, you should read the doc, it's exactly what I explained

**Comment by afwn90cj93201nixr2e1re** [comment]
Bruh, i already made it.. you dont see that pr? You said that you gonna read docs, did you?

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/buefy/buefy/pull/1944#issuecomment-550488842

**Comment by afwn90cj93201nixr2e1re** [comment]
As i said read vue develops comments before discussing things that u don't know @tofandel.

Full vue team said that this options are useless and bo one should use them in practice.
Keep using template's, that's your choice. Im not rude, that just unpopular opinion.

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy as i said in 0.9.0 pr we should remove extra lines, if you don't wanna add this options into compiler config (i agree with that).

**Pull request closed without merging**
