### PR TITLE
Clarify slot property

### PR DESCRIPTION
**Pull request by caleb-allen**
It is unclear in the docs that the `slot` property is necessary

### CODE REVIEW

**Comment by jtommy** [comment]
@caleb-allen Yes there is no Slots tab in API section. Please add it and all slots into in the same way of autocomplete component. 
Thanks

**Comment by caleb-allen** [comment]
@jtommy will do. Where can I find all of the slots options?

**Comment by jtommy** [comment]
In the component code 😁

**Comment by jtommy** [comment]
Please add `default` slot for Dropdown and DropdownItem component too.

**Pull request merged**
