### PR TITLE
Add the row-attribute prop for attribute binding

### PR DESCRIPTION
**Pull request by lunfel**
This is an enhancement for the existing b-table component

## Proposed Changes

Added the ability to bind an attribute object to the table row. It works very similarly to how row-class works. We have a function that receive the row and index parameters and returns an attribute object based on those parameters.

## Example

Here is a simple example to demonstrate the actual usage. This is based on the ExSimple.vue for b-table

```
<template>
    <b-table :data="data" :columns="columns" :row-attributes="attributes"></b-table>
</template>

<script>
    export default {
        data() {
            return {
                data: [
                    { 'id': 1, 'first_name': 'Jesse', 'last_name': 'Simmons', 'date': '2016-10-15 13:43:27', 'gender': 'Male' },
                    { 'id': 2, 'first_name': 'John', 'last_name': 'Jacobs', 'date': '2016-12-15 06:00:53', 'gender': 'Male' },
                    { 'id': 3, 'first_name': 'Tina', 'last_name': 'Gilbert', 'date': '2016-04-26 06:26:28', 'gender': 'Female' },
                    { 'id': 4, 'first_name': 'Clarence', 'last_name': 'Flores', 'date': '2016-04-10 10:28:46', 'gender': 'Male' },
                    { 'id': 5, 'first_name': 'Anne', 'last_name': 'Lee', 'date': '2016-12-06 14:38:38', 'gender': 'Female' }
                ],
                columns: [
                    {
                        field: 'id',
                        label: 'ID',
                        width: '40',
                        numeric: true
                    },
                    {
                        field: 'first_name',
                        label: 'First Name',
                    },
                    {
                        field: 'last_name',
                        label: 'Last Name',
                    },
                    {
                        field: 'date',
                        label: 'Date',
                        centered: true
                    },
                    {
                        field: 'gender',
                        label: 'Gender',
                    }
                ]
            }
        },
        methods: {
            attributes (row, index) {
                if (index < 2) {
                    return {
                        'test-id': row.last_name
                    }
                } else {
                    return {
                        'test-name': row.first_name
                    }
                }
            }
        }
    }
</script>
```

Which will render to:
```
<tbody>
    <tr test-id="Simmons">[...]</tr>
    <tr test-id="Jacobs">[...]</tr>
    <tr test-name="Tina">[...]</tr>
    <tr test-name="Clarence">[...]</tr>
    <tr test-name="Anne">[...]</tr>
</tbody>
```

### CODE REVIEW

**Comment by jtommy** [comment]
Why do you need it? Can you provide a your use case?

**Comment by lunfel** [comment]
I intend to use it in nightwatch.js tests. I use `test-*` attributes instead of css classes for selectors in test cases. Which I find way cleaner since you know that these attributes are only intended for tests and not for styling. tldr, styling the app does not break tests.

```
// Untested code. Just for the sake of an example.
<template>
    <button id="addRowBtn" @click="handleClick">Add Row</button>
    <b-table id="peopleTable" :data="data" :columns="columns" :row-attributes="attributes"></b-table>
</template>

<script>
    export default {
        data() {
            return {
                data: [
                    { 'id': 1, 'first_name': 'Jesse', 'last_name': 'Simmons', 'date': '2016-10-15 13:43:27', 'gender': 'Male' },
                    { 'id': 2, 'first_name': 'John', 'last_name': 'Jacobs', 'date': '2016-12-15 06:00:53', 'gender': 'Male' },
                    { 'id': 3, 'first_name': 'Tina', 'last_name': 'Gilbert', 'date': '2016-04-26 06:26:28', 'gender': 'Female' },
                    { 'id': 4, 'first_name': 'Clarence', 'last_name': 'Flores', 'date': '2016-04-10 10:28:46', 'gender': 'Male' },
                    { 'id': 5, 'first_name': 'Anne', 'last_name': 'Lee', 'date': '2016-12-06 14:38:38', 'gender': 'Female' }
                ],
                columns: [
                    {
                        field: 'id',
                        label: 'ID',
                        width: '40',
                        numeric: true
                    },
                    {
                        field: 'first_name',
                        label: 'First Name',
                    },
                    {
                        field: 'last_name',
                        label: 'Last Name',
                    },
                    {
                        field: 'date',
                        label: 'Date',
                        centered: true
                    },
                    {
                        field: 'gender',
                        label: 'Gender',
                    }
                ]
            }
        },
        methods: {
            handleClick () {
                this.data.push({
                    id: 6,
                    first_name: 'Mathieu',
                    last_name: 'Tanguay',
                    date: '2016-10-18 13:43:27',
                    gender: 'Male'
                })
            },
            attributes (row, index) {
                return {
                    'test-name': `${row.first_name} ${row.last_name}`
                }
            }
        }
    }
</script>

```
The nightwatch.js testcase would look like something like this:
```
// Untested code. Just for the sake of an example.
'Can add a row to the table': browser => {
    browser
      .url(...)
      .click('#addRowBtn')
      .waitForElementVisible('#peopleTable tr[test-name="Mathieu Tanguay"]')
      .assert.containsText('#myTable tr[test-name="Mathieu Tanguay"] td:nth-child(2)', 'Mathieu')
      .assert.containsText('#myTable tr[test-name="Mathieu Tanguay"] td:nth-child(3)', 'Tanguay')
  }
```

**Comment by jtommy** [comment]
@lunfel probably I can merge it but expect your tests I am not able to meet other use cases about your PR,

**Comment by lunfel** [comment]
Not as useful as I tought. I will close PR

**Pull request closed without merging**
