### PR TITLE
Clockpicker

### PR DESCRIPTION
**Pull request by SharpSeeEr**
This is a new Clockpicker component, as discussed in https://github.com/buefy/buefy/issues/753.  This is a full implementation with full docs and tests.

I will note that the scss does use some exact pixel values for padding, height, and width, contrary to the contributing guidelines for buefy.  This is because it was already very difficult calculating lengths and coordinates for the hand and clock face numbers without having to figure in relative values.

Please let me know if I need to make any changes.

### CODE REVIEW

**Comment by jtommy** [comment]
@SharpSeeEr Quick note: could you change class names following Buefy style ? (for example main class `b-clock-picker` and wrap all into this ).
Anyway, great!

**Comment by SharpSeeEr** [comment]
@jtommy I'll get those changes made ASAP!

Any idea why the codecov/patch is failing?  And how to potentially fix it?

**Comment by SharpSeeEr** [comment]
I have made the requested changes, and added proper animation for the clock hand.

**Comment by SharpSeeEr** [comment]
Ping!  I'm not sure what the process is for accepting pull requests, and I'm not trying to push the issue, I'm just excited to see this in the official distribution, mostly so I can start using it directly in my projects.  :)  I'll take no response as "We'll merge it when we are damn good and ready, stop pestering us!"

Thanks!

**Comment by jtommy** [comment]
@SharpSeeEr Thanks for changes. We'll review as soon as possible.

**Comment by jtommy** [comment]
@SharpSeeEr Color example is great but I think it's better have a `type` prop like other components.
Why do you import `TimepickerMixin` in that way ? I think you should use for example `import TimepickerMixinfrom '../../utils/TimepickerMixin`.

**Comment by SharpSeeEr** [comment]
@jtommy I added the type prop to the Clockpicker and updated the docs to use that.  I initially didn't use the property because my preference for my projects is to use the Bulma classes, and only use a component prop when necessary.  But that is my preference, and I see the need to have this consistent across the library.  

I updated the import clause.  Not sure why I formatted it that way originally, but it now is simply `import TimepickerMixin from '../../utils/TimepickerMixin'`

While there I noticed the inline Clockpicker showed a 0 for the hour when 12 is selected, so I fixed that as well.

Please let me know if there is anything else I should change.

**Comment by SharpSeeEr** [comment]
Any update on merging this?

**Comment by SharpSeeEr** [comment]
I merged the upstream changes into my branch and resolved the conflicts.

**Comment by jtommy** [comment]
@SharpSeeEr Thanks! 
We're testing new single components build so we have to think if add your component in the next release or after it.

**Comment by jtommy** [comment]
@SharpSeeEr We're quite ready to review it but meanwhile you might resolve conflicts.

**Comment by SharpSeeEr** [comment]
Updated pull request integrating current buefy/dev.

**Comment by jtommy** [comment]
@SharpSeeEr Great! Thanks a lot!

**Pull request merged**
