### PR TITLE
BREAKING WIP: Update to Bulma 0.8.0

### LINKED ISSUE #2076: Support Bulma 0.8.0
Any idea when Buefy will start supporting Bulma 0.8.0 and/or it supports it already? 

The new version of Bulma has some nice new features we want to use, but we are waiting for Buefy to be 100% that everything will work.

### PR DESCRIPTION
**Pull request by service-paradis**
Fixes #2076

## Proposed Changes

- Update Bulma to 0.8.0
- Use `$scheme` variables
- Update doc for Button light colors

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
Nice.
But can you write something about merging to 0.8 for guy's which r using importing custom scss instead using built in.

And little bit about why it was removed.
It was temp. solution?
изображение

**Comment by service-paradis** [comment]
@afwn90cj93201nixr2e1re 
It is still in WIP. When it will be ready to merge, I will add needed notes. It would be in a breaking release anyway.

About the removing, I'm not sure what you're talking about since it is still there:
image

**Comment by afwn90cj93201nixr2e1re** [comment]
Hm, strange, that's stilll show me like u delete this section, lol.

**Comment by wopian** [comment]
They were looking at the rebase commit (from upstream/master) instead of the actual changes in the PR.

**Comment by afwn90cj93201nixr2e1re** [comment]
oh, get u, yep, missed.

**Comment by M1CK431** [comment]
Hi,

Not sure if it's relevant (especially for a WIP) but Bulma tags also gain a light color variant in v0.8.0:
https://bulma.io/documentation/elements/tag/#colors

Thanks a lot for your good work :+1:

**Comment by service-paradis** [comment]
@M1CK431 
Thanks for your comment. Indeed, it works for tags. I added an example to be clearer about it :)

**Comment by frellan** [comment]
@service-paradis How is it going on this? Is there anything you need help with? I need bulma 0.8.0 :)

**Comment by jtommy** [comment]
@frellan we are waiting for 0.8.2 because there is an important fixed issue

**Comment by Juneezee** [comment]
[Bulma 0.8.2 is out](https://github.com/jgthms/bulma/releases/tag/0.8.2).

**Pull request merged**
