### PR TITLE
Feature: Adds autocomplete slot support to taginput

### PR DESCRIPTION
**Pull request by gkinsman**
Brings feature parity between taginput and autocomplete by passing taginput's slots through to the underlying autocomplete.

image

image

### CODE REVIEW

**Comment by jtommy** [comment]
@gkinsman Great idea! To be honest i'm thinking a way to avoid that code:
```
defaultSlotName() {
    return this.hasDefaultSlot ? 'default' : 'dontrender'
 },
 emptySlotName() {
      return this.hasEmptySlot ? 'empty' : 'dontrender'
 },
```
I don't like have a fake slot name, what do you think ?

**Comment by gkinsman** [comment]
I agree, although without the dummy slot name, the replacement slot will always be rendered instead of the autocomplete default. One alternative would be to duplicate the default from autocomplete but I decided against that. 

There doesn't seem to be a way to tell a nested component like this whether it should use the default slot or not - except for this method. In that sense, I think using 'dontrender' makes some sense.

**Comment by jtommy** [comment]
@gkinsman Thanks but it could be changed if we find an elegant way

**Comment by yakovyarmo** [comment]
why can't you use something like:
`                <template v-if="hasDefaultSlot">
                    <template slot-scope="props">
                        <slot
                          :option="props.option"
                          :index="props.index" />
                    </template>
                </template>`

**Pull request merged**
