### PR TITLE
Fix hidden overflow inside tab

### LINKED ISSUE #468: Taginput autocomplete limited by tabs
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.9]
**OS/Browser**: Firefox / Chrome

### Description

When using b-taginput autocomplete within b-tabs the dropdownlist is behind the content below the b-tab.

### Steps to reproduce

`
                            <b-tabs v-model="activeTab">
                                <b-tab-item label="Aan">
                                    <b-taginput
                                            v-model="aan"
                                            :data="filteredTags"
                                            autocomplete
                                            field="username"
                                            icon="label"
                                            placeholder="Bericht aan"
                                            @typing="getFilteredTags"
                                    >
                                    </b-taginput>
                                    <br>
                                </b-tab-item>
                                <b-tab-item label="CC">
                                    <b-taginput
                                            v-model="cc"
                                            :data="filteredTags"
                                            autocomplete
                                            field="username"
                                            icon="label"
                                            placeholder="Bericht aan cc"
                                            @typing="getFilteredTags"
                                    >
                                    </b-taginput>
                                </b-tab-item>
                                <b-tab-item label="BCC">
                                    <b-taginput
                                            v-model="bcc"
                                            :data="filteredTags"
                                            autocomplete
                                            field="username"
                                            icon="label"
                                            placeholder="Bericht aan bcc"
                                            @typing="getFilteredTags"
                                    >
                                    </b-taginput>
                                </b-tab-item>
                            </b-tabs>
`
### Expected behavior

Autocomplete dropdown is always in front 

### Actual behavior
Autocomplete dropdown is beheind content. 
I used a `<br>` to see one option. It has to display a lot more
afbeelding

### LINKED ISSUE #808: b-datepicker is hidden by b-tab
### Overview of the problem

Buefy version: [5.6.0]
Vuejs version: [5.6.0]
OS/Browser: Chrome:
screen shot 05-11-18 at 02 26 pm

### Description

The b-datepicker is hidding behind the b-tab and not able to see the calendar.  Is there anyway to fix this quickly?
 
### Steps to reproduce
```

      @extends('layouts.test')


      @section('content')


       
          <strong slot="header" >Testing 123
          </strong>

          <div class="content">      
            <b-tabs >
              <b-tab-item label="Pictures">
                <b-field label="Select a date">
                    <b-datepicker
                        placeholder="Click to select..."
                        icon="calendar-today">
                    </b-datepicker>
                </b-field>                  
              </b-tab-item>

              <b-tab-item label="Music">
                  Lorem <br>
                  ipsum <br>
                  dolor <br>
                  sit <br>
                  amet.
              </b-tab-item>    
            </b-tabs>        
          </div>

      @endsection


      @section('scripts')

      <script type="text/javascript">
      

        var App = new Vue({
            el: '#app',
            data: {
            },
            methods: {
            },
          });

      </script>

      @endsection 



```

### Expected behavior
To be able to select the calendar

### Actual behavior

tab is hiding the calendar

### PR DESCRIPTION
**Pull request by Baggs**
I have created improved version of #811 PR

Before:
image
After:
image

overflow:hidden is applied to tab-content only during animated tab transition to avoid below problem (it was noticed in #811 comments)

image

In my PR it looks like that:
image

I am sorry for creating another PR but I don't know if it's possible to amend someone else's PR.

closes #808 
closes #468

### CODE REVIEW

**Comment by jtommy** [comment]
I'll take look as soon as possible

**Comment by LazyBun** [comment]
Would it be possible to get this merged?

**Comment by LazyBun** [comment]
https://www.npmjs.com/package/buefy-956
I've created forked version of buefy with this fix merged - in case anybody wants it

**Comment by jtommy** [comment]
@Baggs can you resolve the conflicts in order to merge it ?

**Comment by Baggs** [comment]
I am sorry for not resolving the conflicts on time. Thank you for moving the changes to dev yourself. I see this has already been released as part of 0.7.4.

**Comment by jtommy** [comment]
Oh yes, I added you in the changelog anyway

**Pull request closed without merging**
