### PR TITLE
Added tab keycode to confirmKeyCodes in Taginput.vue

### PR DESCRIPTION
**Pull request by williamabbott**
I think this resolves the issue. #973

### CODE REVIEW

**Comment by jtommy** [comment]
@williamabbott What issue has been fixed ?

**Comment by williamabbott** [comment]
See referenced issue.. Taginput on mobile doesnt add the tag. When in android for example the only confirm button you get on the keyboard actually tabs to the next field instead of entering. I added tab keycode.

**Comment by williamabbott** [comment]
(when 'add new' is active)

**Comment by tycrimm** [comment]
This breaks the ability to tab from a TagInput to another form component for the sake of the mobile fix. Reverting the PR allows the user to once again tab between input components on a desktop. Can we find a better workaround for mobile so we don't break the desktop experience?

**Pull request merged**
