### PR TITLE
Rebase Changes in Kikuomax/Buefy#Vue-3 on Top of Buefy/Buefy#Dev.

### PR DESCRIPTION
**Pull request by kikuomax**
## Proposed Changes

- I have made a version of Buefy that works on top of **Vue 3**.
- Changes have been made **based on v0.9.7** as I started migration about two month ago.
- My migration goal was to **make the documentation page of every component work** (no error logs, and no obvious visual flaw). No tests have been updated.
- It **does not work with Vue 2**.
- You can install this version with `npm install 'git+https://github.com/kikuomax/buefy.git'`.
- There are too many changes, so please refer to [README](https://github.com/kikuomax/buefy/blob/vue-3/README.md), [CHANGELOG](https://github.com/kikuomax/buefy/blob/vue-3/CHANGELOG.md), and [MIGRATION-NOTE](https://github.com/kikuomax/buefy/blob/vue-3/MIGRATION-NOTE.md) of my fork for more details.
- I do not think this PR is acceptable, but I hope this could be a good material for Vue 3 support.

### CODE REVIEW

**Comment by holtolee** [comment]
Thank you for your work, used it for migrating a big project to Vue 3 and Typescript.
I had the named `v-slot` problem with component in `b-table` (fixed it) and `b-collapse` (removed `b-collapse` and used `v-if` instead) any news on this ?
Also i had to replace `b-button` with `button` with button class because `@click` wasn't working but everything else was good.

**Comment by kde99** [comment]
Hello. 

Any chance for this to be updated for 0.9.20? It produces quite a few merge conflicts.

Thank you for your work so far.

**Comment by dword-design** [comment]
Hey, what's the current state of this? Are there plans to merge it?

**Comment by kaangokdemir** [comment]
> Hey, what's the current state of this? Are there plans to merge it? I saw that there is also this project https://github.com/yooouuri/bulma-vue.

Unfortunately maintainer @jtommy stated in Discord that he does not have time for maintaining two similar open-source projects (Oruga is the other one which he's maintaining)

I don't know and also wonder if @jtommy is interesting to handover the Buefy to either @kikuomax, @yooouuri or anyone who wants to maintain and migrate into Vue3.

**Comment by dword-design** [comment]
Ok and what's the state of this PR? @kikuomax It looks like a lot of work has already been put into it 😊.

**Comment by dagnelies** [comment]
Indeed, it would be sad to lose this hard work.

Since this vue3 fork is incompatible with vue2, it might even make sense to keep it as a separate project.

Perhaps rebranding @kikuomax's fork as "buefy3" to emphasize the vue3 compatibility. Although it's a bit strange to skip the "buefy2". Or perhaps even pick another name, like "vulma" (vue+bulma), dunno.

That way, bulma keeps the way it is and remains compatible, which is important for all the existing projects out there. And for those wanting to use the vue3 version, the new project would be available. What would be important and probably sufficient is to add a disclaimer on the front page like:

> Lightweight UI components for [Vue.js 2](https://v2.vuejs.org/) based on [Bulma](http://bulma.io/)
> For Vue.js 3, please take a look a [this project](https://github.com/kikuomax)

**Comment by kikuomax** [comment]
@dword-design @kaangokdemir @dagnelies @jtommy Thanks a lot for your attentions.

@dagnelies 
> Since this vue3 fork is incompatible with vue2 and vice versa, it might even make sense to keep it as a separate project. Separate npm package name, separate tickets, etc.

I found it very difficult to make my fork compatible with Vue2. So it makes sense to me, having a separate project.

@jtommy
> I might release it, but someone must test the PR

I would like to port `*.spec.js` files when I have time.

**Comment by holtolee** [comment]
> I have completely rebased my fork from **v0.9.21**. Please refer to updated [README](https://github.com/kikuomax/buefy/blob/vue-3/README.md), [CHANGELOG](https://github.com/kikuomax/buefy/blob/vue-3/CHANGELOG.md), and [MIGRATION-NOTE](https://github.com/kikuomax/buefy/blob/vue-3/MIGRATION-NOTE.md) for more details.
> 
> @holtolee As I could not reproduce your issues, the problems may persist.
> 
> @kde99 My fork is now based on v0.9.21.

I just rebased my almost 2 years old wip branch (migrating vue 2 to vue 3 + Typescript and vue-cli to Vite) 
I will keep you in touch and if we can make this PR released it would be awesome 🚀 

Thanks again @kikuomax and @jtommy for your work ✌🏻

**Comment by holtolee** [comment]
> I just rebased my almost 2 years old wip branch (migrating vue 2 to vue 3 + Typescript and vue-cli to Vite) I will keep you in touch and if we can make this PR released it would be awesome rocket
> 
> Thanks again @kikuomax and @jtommy for your work ✌🏻

My only issues remaining are not Buefy related and i am almost done migrating my project.

(261 files +21024 -11756)

Search results in the project for buefy components `<b-` : 495 in 115 files.

The work of @kikuomax seems pretty stable.

**Comment by kyle-jennings** [comment]
> @dword-design @kaangokdemir @dagnelies @jtommy Thanks a lot for your attentions.
> 
> @dagnelies
> 
> > Since this vue3 fork is incompatible with vue2 and vice versa, it might even make sense to keep it as a separate project. Separate npm package name, separate tickets, etc.
> 
> I found it very difficult to make my fork compatible with Vue2. So it makes sense to me, having a separate project.
> 
> @jtommy
> 
> > I might release it, but someone must test the PR
> 
> I would like to port `*.spec.js` files when I have time.

Could we maybe merge it into the Buefy repo but named something like "buefy-3"?

Oruga uses "-next" to denote the Vue3 version of Oruga but I think "-3" makes more sense as the meaning of "next" changes depending on what the current version is.

**Comment by ElteHupkes** [comment]
I too have migrated a project to this version and didn't run into any problems apart from some erroneous TypeScript definitions. I'm willing to help, although the entirety of my experience with Vue spans the back half of 2022 until now, so when it comes to framework experience I'm probably out of my depth. Don't mind getting into the weeds though.

**Comment by dword-design** [comment]
Published this to [@dword-design/buefy](https://www.npmjs.com/package/@dword-design/buefy) in case someone wants to use it.

**Comment by messenjer** [comment]
> Published this to [@dword-design/buefy](https://www.npmjs.com/package/@dword-design/buefy) in case someone wants to use it.

Hi, I started to migrate a huge application from vue2 to vue3 using this package and it works very well. This is the first time I use Bueify, so I'm doing components by components.

I would like to get involved to make this fork sustainable, what are the missing steps? 
* convert the tests
* publishing the packages for vue3
* ...

Thanks for this work @kikuomax , @dword-design 

Mathieu

**Comment by holtolee** [comment]
> I might release it, but someone must test the PR

Any progress ? 👀

**Comment by kyle-jennings** [comment]
> Published this to [@dword-design/buefy](https://www.npmjs.com/package/@dword-design/buefy) in case someone wants to use it.

Looks like this is based on what @kikuomax made? (https://github.com/kikuomax/buefy) can you give them a large shout out on the NPM page and update the repo link to https://github.com/kikuomax/buefy?

Maybe this will get enough traction at https://github.com/kikuomax/buefy so we can get some more updates rolled in, or some more contributors/co-owners to approve PRs

**Comment by wesdevpro** [comment]
All development for Buefy Vue3 has been moved to [ntohq/buefy](https://github.com/ntohq/buefy). The goal of the ntohq fork is not to replace [Buefy](https://github.com/buefy/buefy), but to separate the current version from the migration to Buefy Vue3. If you would like to help contribute join the official discords for Buefy and Buefy Vue3 Development ( [Buefy Discord](https://discordapp.com/invite/ZkdFJMr), [ntohq discord](https://ntohqdevelopers.com/discord)). A Development plan will soon be released for what this migration means for both Buefy Vue2 and Buefy Vue3. If you have any questions, please communicate them over the discord.

**Pull request closed without merging**
