### PR TITLE
Release 0.9.28

### PR DESCRIPTION
**Pull request by kikuomax**
Fixes #
- #4009 

## Proposed Changes

- Include the changes made since v0.9.27, which we already have reviewed

**Please do not use any merge options on GitHub!**

### CODE REVIEW

**Review by wesdevpro — APPROVED** [review]
LGTM ⚒

**Comment by miroslavgeorgiev** [comment]
@kikuomax - would you bump the Nuxt version as well 🙏

**Comment by wesdevpro** [comment]
> @kikuomax - would you bump the Nuxt version as well 🙏

Working on that right now. Once @kikuomax reviews my PR those changes will be made for the nuxt-buefy package.

**Comment by wesdevpro** [comment]
> @kikuomax - would you bump the Nuxt version as well 🙏

https://github.com/buefy/nuxt-buefy/releases/tag/v0.4.28

**Pull request merged**
