### PR TITLE
Replace Object.assign with custom merge function

### PR DESCRIPTION
**Pull request by service-paradis**
As discussed in Discord with @jtommy , here is a PR that fix IE11 problems with Object.assign.

## Proposed Changes

- Replace Object.assign with custom merge function

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
Why we should replace standart function, with custom stuff with spread operator inside?

**Comment by afwn90cj93201nixr2e1re** [comment]
Why we cant just use spread operator?

**Comment by afwn90cj93201nixr2e1re** [comment]
Vue using object spread/assign, why we should use another one for simple object without any nesting stuff?

@service-paradis

**Comment by afwn90cj93201nixr2e1re** [comment]
> As discussed in Discord with @jtommy
In pm? Nothing was found in chats.
Again

**Comment by afwn90cj93201nixr2e1re** [comment]
Maybe now you should refactor custom merge? (If it's have deep merging support, add new param and check is there Object.assign support or not, sometimes object assign faster 100x times and spread faster 2000x on chrome and guaranteeing no memory leaks on object's).

But i still dont get why we cant just use spread operator here if its simple object's.

**Comment by service-paradis** [comment]
#1934

**Pull request merged**
