### PR TITLE
Change the tabs logic to provide/inject and add support for ids in v-model

### PR DESCRIPTION
**Pull request by Tofandel**
Fixes ##2498 #2557 #1026

## Proposed Changes
The logic is now simplified by Vue provide/inject
The internal state has been modified to work with ids, the external state can work with indexes or ids as such keeping backward compatibility

If a number is provided the input will always emit a number, if an id is provided it will always emit a string id

Only breaking change:
The change event was removed, as it's not useful and was acting as a duplicate of input

Thoroughly tested with unit test and doc included

### CODE REVIEW

**Comment by jtommy** [comment]
Why did you add Id prop ? There is already value prop on tabitem to use a string value instead of an index.

**Comment by Tofandel** [comment]
Mm, guess I completely missed it, I'll just change id to value

**Comment by Tofandel** [comment]
Quick question, is it okay if I also include a version change of node-sass in package.json
It doesn't compile with the latest node with the current version (https://github.com/nodejs/node-gyp/issues/1960) and I have to update it every time

**Comment by jtommy** [comment]
About node-sass I think to remove it and use dart-sass

**Comment by Tofandel** [comment]
That's a good idea, I'm using it for projects using buefy and it does solve some problems at the price of some compilation time, there is also quite a few other libraries that need an update (eg @vue/test-utils)
So I won't include it here, PR is done

**Pull request merged**
