### PR TITLE
Add trim option for v-model stuff.

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**
Fixes #

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy can we add .number .integer .float and other stuff before releasing?

**Comment by service-paradis** [comment]
You can use `v-model.trim` on `b-input` component. The prop is not really useful I think.

**Comment by afwn90cj93201nixr2e1re** [comment]
Try it.

**Comment by service-paradis** [comment]
I already use it (https://codepen.io/service-paradis/pen/rNNPwGO?&editable=true&editors=101).

Type something in the 1st input with spaces at the end. It will be displayed as `"something"`.
Type something in the 2nd input with spaces at the end. It will be displayed as `"something "`.

**Comment by afwn90cj93201nixr2e1re** [comment]
изображение

For more info: #1990


So, seems like we gonna create cb/function with pre validating/changing for fix desync.

Pr is not gonna be merged.

**Comment by service-paradis** [comment]
I dont understand what you mean. In the image you just posted, the value below the input is trimmed like it should.

**Comment by afwn90cj93201nixr2e1re** [comment]
Value is trimmed. so and?
Is that synced? No.

**Comment by service-paradis** [comment]
Your PR is about adding a prop to trim values. Value is trim. PR can be closed.

The syncing problem is note related to this PR...

**Comment by afwn90cj93201nixr2e1re** [comment]
:/ Read previous comments.

**Comment by jtommy** [comment]
Double

**Pull request closed without merging**
