### PR TITLE
docs: add Cloud IDE preview link

### PR DESCRIPTION
**Pull request by icarusion**
Add Cloud IDE link to view code and preview buefy components online.

### CODE REVIEW

**Comment by jtommy** [comment]
Are you sure? It doesn't work.. i added to revert it

**Comment by icarusion** [comment]
It works.
image
Depends on `preview.yml` file.

**Comment by jtommy** [comment]
Ok, send me again the PR

**Comment by icarusion** [comment]
Ok, thanks. The new PR is #3814

**Pull request merged**
