### PR TITLE
Added scrollTo for all form elements

### PR DESCRIPTION
**Pull request by karimvally1**
## Proposed Changes

Adding support for scrollTo element using the HTML scrollIntoView function.

### CODE REVIEW

**Comment by jtommy** [comment]
Why do you need it ? I don't understand why do you think it's a good feature to add in the core code

**Comment by karimvally1** [comment]
> Why do you need it ? I don't understand why do you think it's a good feature to add in the core code

It's a good feature because it exposes the underlying HTML5 function to scroll to element which is useful for invalid states from a user experience point of view. In my case, a long form which has an invalid input using the scroll to function would bring the invalid state to the users attention.

**Comment by jtommy** [comment]
@karimvally1 can you provide me a code example about it ?

**Comment by jtommy** [comment]
I think it isn't an added value adding it in the core code at the moment.  
Maybe in a future form validation feature.
Btw thanks!

**Pull request closed without merging**
