### PR TITLE
Add new parameter in b-taginput of validation

### PR DESCRIPTION
**Pull request by brunoosilva**
You can validate the value before adding it to the tag list

### CODE REVIEW

**Comment by jtommy** [comment]
@brunoosilva Please resolve conflicts and I think it's better change name of prop to `beforeAdding` or similar

**Comment by jtommy** [comment]
Thanks but please remove changelog commit because we have to decide when release this PR.

**Comment by brunoosilva** [comment]
@jtommy When it is done new release with this feature ?

**Comment by jtommy** [comment]
As soon as possible. Stay tuned!

**Pull request merged**
