### PR TITLE
Fix Datepicker. Date now can be set from a string

### PR DESCRIPTION
**Pull request by Sillanium**
Hi all. It is my solution for issue https://github.com/buefy/buefy/issues/700

### CODE REVIEW

**Comment by jtommy** [comment]
@Sillanium `dateParser` has an other scope as I described for https://github.com/buefy/buefy/issues/700

**Comment by Sillanium** [comment]
@jtommy in my case date comes from server (MySQL DB). It works fine.
Maybe add "modelParse" method with default value be "dateParser" value ?

**Comment by jtommy** [comment]
@Sillanium Yes maybe it could be a good way but I should think about names.

**Comment by Sillanium** [comment]
@jtommy Ok. Tell me about your resolution, please. I can contribute

**Comment by jtommy** [comment]
We should rethink the component to add somenthing about

**Comment by elmatou** [comment]
I understand this has not been merged and the possibility to send Date as string is not yet implemented.

Any reason, since it is a quit old issue (#700) ?

**Pull request closed without merging**
