### PR TITLE
dropdown trigger-tabindex prop

### LINKED ISSUE #3433: datepicker keyboard tab navigation
### Overview of the problem

**Buefy** version: [0.9.8]
**Vuejs** version: [2.6.12]
**OS/Browser**: Linux, Firefox 90

### Description

Keyboard tab navigation doesn't stop into INPUT element of DatePicker, focusing the outer container instead. It was working fine on previous versions (at least 0.9.3)

### Steps to reproduce

Open buefy documentation, "editable" section. Try to navigate using keyboard. You'll have to press TAB twice for keyboard cursor to stop inside DatePicker.

### Expected behavior

Press TAB once to focus DatePicker

### Actual behavior

You need to press TAB twice. First TAB focus the outer frame of DatePicker. Second TAB finally moves focus to INPUT element.

### PR DESCRIPTION
**Pull request by Spacarar**
Fixes #3433

## Proposed Changes
- add trigger-tabindex to dropdown component (Number default 0)
- set datepicker's dropdown trigger-tabindex to -1 to prevent extra tab selection

### CODE REVIEW

**Comment by grantmcconnaughey** [comment]
Hey @jtommy, any chance a new release could be cut which includes this change? This would fix an issue I'm running into where Dropdown's non-overridable tabindex is causing funky tab navigation in my app. Thanks!

**Comment by jtommy** [comment]
I hope to make a new one next week

**Comment by grantmcconnaughey** [comment]
Awesome! Thank you so much. 🙏

**Comment by jtommy** [comment]
@grantmcconnaughey https://github.com/buefy/buefy/commit/1d8ede598eaf1c3c731571297fb8f1ac0eb4fd9f just released

**Comment by grantmcconnaughey** [comment]
Awesome, thank you!

**Pull request merged**
