### PR TITLE
Fix to show copyright in rollup minify

### PR DESCRIPTION
**Pull request by apolokaklab**
I Add comment copyright in rollup minify.
@jtommy  for next, can you add option for dist output tree shake (component) to inculde or not.
i have component carousel and rate (rating) with vue and bulma, can i share to here? thanks.

### CODE REVIEW

**Comment by jtommy** [comment]
Do you want to share your 2 components in Buefy?

**Comment by apolokaklab** [comment]
yes, but the component is not included in the Buefy Roadmap :(

**Comment by jtommy** [comment]
It's no a problem, you are free to make a PRs

**Comment by jtommy** [comment]
Added manually to fix other issue, thanks

**Comment by apolokaklab** [comment]
Nice, oke no problem.
and Can you update package ``node-sass`` to ``^4.12.0``? because for node.js v12 use node-sass version min 4.12.0.

**Pull request closed without merging**
