### PR TITLE
Change order to prevent slot from messing with focus

### PR DESCRIPTION
**Pull request by GMartigny**
Fixes #

## Proposed Changes

- Change order of tag inside Upload component

### CODE REVIEW

**Comment by GMartigny** [comment]
Bug reproduction :
1. Go to https://codepen.io/GMartigny/pen/eYwmOwx?editors=1010
2. Add a file to the Upload component
3. See that you can update the file, because the focus goes to the text input

**Comment by wesdevpro** [comment]
> Bug reproduction :
> 
> 1. Go to https://codepen.io/GMartigny/pen/eYwmOwx?editors=1010
> 2. Add a file to the Upload component
> 3. See that you can update the file, because the focus goes to the text input

@kikuomax the bug was reproducible on my end.

**Comment by wesdevpro** [comment]
> @GMartigny @kikuomax the bug was reproducible on my end.

@GMartigny do you know if this is also ab issue with Buefy-next?

**Comment by GMartigny** [comment]
> @GMartigny do you know if this is also an issue with Buefy-next?

It is, since tags are in the same order there too. https://github.com/ntohq/buefy-next/blob/dev/packages/buefy-next/src/components/upload/Upload.vue#L7-L9

**Comment by wesdevpro** [comment]
> > @GMartigny do you know if this is also an issue with Buefy-next?
> 
> 
> 
> It is, since tags are in the same order there too. https://github.com/ntohq/buefy-next/blob/dev/packages/buefy-next/src/components/upload/Upload.vue#L7-L9

That makes sense. Could you also make a PR there as well?

**Review by wesdevpro — APPROVED** [review]
I have not tested this component but logically this makes sense and the code changes look good. Please wait for @kikuomax to review. I will also take sometime to test these changes to see if I find any abnormal behaviors from the component

**Review by kikuomax — APPROVED** [review]
@GMartigny I have confirmed your PR fixes the issue.

Btw, I was wondering why the order mattered. According to the [MDN documentation about `<label>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label):
> When a user clicks or touches/taps a label, the browser passes the focus to its associated input (the resulting event is also raised for the input).

I am not 100% sure about the behavior of `<label>` when it contains multiple nested `<input>` elements, though, it makes sense if the first `<input>` gets the focus.

Another possible workaround might be to add the `for="unique-upload-id"` attribute to `<label>`, and the `id="unique-upload-id"` to `<input>`. However, we have to make sure `unique-upload-id` globally unique to adopt this approach.

**Comment by GMartigny** [comment]
> Btw, I was wondering why the order mattered.

As you expected, when a `<label>` has multiple focusable element inside, the first one get it.

Also, yes, it would be possible (I guess) to generate random id an attribute it to the `<input type="upload">` and `<label>`. With a large enough cryptographic randomness, collision chances are pretty much 0.

**Pull request merged**
