### PR TITLE
closeOnSelect to autocomplete, added to taginput docs

### PR DESCRIPTION
**Pull request by williamabbott**
#577

### CODE REVIEW

**Comment by jtommy** [comment]
@williamabbott I tested but I didn't found any difference when that prop is enabled or not to be honest

**Comment by williamabbott** [comment]
@jtommy seeing some strange behaviour with autocomplete, by adding 'open-on-focus', sometimes the dropdown stays open for 2 or 3 selections. When it disappears, it's visibility is gone, but clicking in that area can select some options (this is from the dev branch with mods only to the taginput docs) gif:

autocomplete

**Comment by jtommy** [comment]
Thanks. I think it's better to know when and why there is that strange behaviour before to add a new prop

**Comment by williamabbott** [comment]
I have narrowed this bug down to the transition group that wraps around Autocomplete's dropdown-menu leaves the class `.fade-leave-to` ( opacity: 0 ) 

image

See the invisible selection on left. I think it could be related to this reported bug: https://github.com/vuejs/vue/issues/5800

**Pull request closed without merging**
