### PR TITLE
fixed datepicker v-model on ios devices

### LINKED ISSUE #1834: DatePicker sets invalid date on iOS Safari
### Overview of the problem

**Buefy** version: 0.8.5
**Vuejs** version: 2.6.10
**OS/Browser**: iOS 13 / Safari

### Description

Using a date picker on iOS with Safari always produces an "invalid date".
This happens on iOS 12 & iOS 13 but not on macOS Safari 12 & 13.
This makes date pickers unusable on iPhone/iPad.
This is similar to #1516 I reported earlier this year, that was fixed quickly.
Now both normal date pickers and month pickers don't work anymore.
I don't know in which Buefy Version this broke but 0.8.3 already has this problem.
Note that when initializing the v-model value, the date picker shows the correct date.
As soon as the date is then changed via the date picker, the date becomes invalid.

### Steps to reproduce

1. Open https://codepen.io/melvinfrohike/pen/LYYYdVV in iOS Safari.
2. Select any date

### Expected behavior
The 'selected date' label should show the selected date's string representation

### Actual behavior
The 'selected date' label shows "invalid date".

### PR DESCRIPTION
**Pull request by bohdan-prylutskyi**
Fixes #1834

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by jtommy** [comment]
@bohdan-prylutskyi did you test it on Android device too ?

**Comment by jtommy** [comment]
Checking the history I found out that I added time part because there was an issue about timezone https://github.com/bohdan-prylutskyi/buefy/commit/3f7bb8fe401e6a6722ef0ec7d28c1d418b6d80ad

**Comment by service-paradis** [comment]
I think, the best way to make this compatible with any browsers would be to use the `Date` constructor this way:
`new Date(year, month, day, hours, minutes, seconds)`

The function could look like this:
```
onChangeNativePicker(event) {
    const date = event.target.value
    let dateParams = []
    if (date) {
        dateParams = `${date} 00:00:00`.split(/[\s-:]/)
    }
    this.computedValue = date ? new Date(...dateParams) : null
}
```

Would need to be tested!

**Comment by bohdan-prylutskyi** [comment]
@jtommy  yeah, i see. The problem is that Safari doesn't support such format 
`YYYY-MM-DD 00:00:00` for new Date(). 
According to this https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse we can pass: 
`YYYY-MM-DDT00:00:00` that will fix the issue but it will add timezone offset to time in Safari.

**Comment by jtommy** [comment]
Ok, please add it

**Comment by service-paradis** [comment]
Just removing the hours bring back the problem from #1591.
You can see it in https://github.com/buefy/buefy/issues/1957.

**Pull request merged**
