### PR TITLE
Refactoring bundle build and add single components build

### PR DESCRIPTION
**Pull request by jtommy**

### CODE REVIEW

**Comment by sinanerdem** [comment]
Thank you for the commit. I want to test the dev version. How to use tree picking? How to import a specific component?

And also I am trying to install dev branch as: 
npm i -D buefy/buefy#dev
Is it correct?

**Comment by jtommy** [comment]
@sinanerdem Docs in the dev branch has been updated and you might follow it. 
For example::
```
import Vue from 'vue'
import Table from 'buefy/dist/components/table'
import Input from 'buefy/dist/components/input'
import 'buefy/dist/buefy.css'
Vue.use(Table)
Vue.use(Input)
```
To install a unpublished package I usually use:
npm install username/repo#branchName --save

**Comment by rafaelpimpa** [comment]
Try installing with

```
npm install buefy@beta
```
Should have this version with new build settings.

**Comment by sinanerdem** [comment]
Thank you. Everything seems to work except dialog. Its usage is a bit different. How can I use it?

**Comment by jtommy** [comment]
Did you add `Vue.use(Dialog)` and then `this.$dialog.` ?

**Pull request merged**
