### PR TITLE
Component proposal: Steps

### PR DESCRIPTION
**Pull request by service-paradis**
Hello,

I needed to use a component in one of my projects. I was using [Bulma Steps](https://wikiki.github.io/components/steps/) and thought that it would be great to have tis kind of component in Buefy.

So I made one inpired by Bulma Steps and Buefy Tabs.

localhost_9999_documentation_steps

Please let me kow what you think about it!

### CODE REVIEW

**Comment by jtommy** [comment]
@service-paradis The components is great, but I think we should mention Bulma Steps license in the _steps.scss file

**Comment by service-paradis** [comment]
@jtommy 
Sure! Is something like thiscorrect?

**Comment by jtommy** [comment]
Sure!

**Comment by service-paradis** [comment]
Thanks!

**Comment by service-paradis** [comment]
Oups, there are typos in the documentation for the property `has-navigation`.

**Comment by jtommy** [comment]
You are free to fix it in other PR ;)

**Pull request merged**
