### PR TITLE
Make tableColumn headerSelectable prop default to false

### PR DESCRIPTION
**Pull request by raimondlume**
## Proposed Changes
Make the headerSelectable prop of TableColumn default to false, as discussed in #2302.

### CODE REVIEW

**Comment by service-paradis** [comment]
Thanks for the contributions!
I'm asking myself a question about this. I agree that header text should not be selectable by default when they are clickable (ex. for sorting).
I'm not sure about this default when header are not clickable though. What do you think?

**Comment by jtommy** [comment]
@service-paradis you are right, looking other libs it's no a default behaviour

**Comment by raimondlume** [comment]
> I'm not sure about this default when header are not clickable though. What do you think?

I agree as well, will change this when I have a moment again.

**Comment by raimondlume** [comment]
How's this? This line is getting a bit long, should the conditon be moved to a computed property?

**Comment by service-paradis** [comment]
Could be a good idea to add this in a computed property. Would maybe need to change the name or improve the documentation to warn user that this is affecting only sortable column.

**Comment by raimondlume** [comment]
"sortableHeaderSelectable" feels a bit too verbose, so maybe let's stick with better documentation? :smile:

**Pull request merged**
