### PR TITLE
Useless input emits fix

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**
Fixes #

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by jtommy** [comment]
Why do you need it? It should be avoided by css

**Comment by afwn90cj93201nixr2e1re** [comment]
How it can be avoided by css?
Coz if user click on active tab, click also emited, i think it shouldn't.

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/blob/ef279334a259bfd3877f4cbf2cea6d4b5567840f/src/scss/components/_tabs.scss#L6

**Comment by afwn90cj93201nixr2e1re** [comment]
So, we should add is-disabled to active tab or what?

**Comment by jtommy** [comment]
Why do you want exclude click to not active tab ?

**Comment by afwn90cj93201nixr2e1re** [comment]
I want exclude click on active tab, coz it's spaming now on clicks with input event, check one more time condition which was added. If it's not active tab then emit input.

**Comment by jtommy** [comment]
I don't know if it makes sense but maybe a user wants to listen a click before changing the current tab so it could be a bug or a breaking change :smile:

**Comment by afwn90cj93201nixr2e1re** [comment]
Really dont get it. How he can do it?
Click before changing gonna call not same item.

It's blocking emits only on clicking on current (active) tab.

**Comment by jtommy** [comment]
I'm sorry, you are right. Please put the check in the methods and not in the template

**Comment by afwn90cj93201nixr2e1re** [comment]
Ok.

**Comment by afwn90cj93201nixr2e1re** [comment]
Ready.

**Comment by jtommy** [comment]
Thanks

**Comment by afwn90cj93201nixr2e1re** [comment]
What do you think about useless emit's inside table?

**Comment by jtommy** [comment]
For example?

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/buefy/buefy/blob/dev/src/components/table/Table.vue#L142

It's also spaming. but im not using any drag and drop stuff.

**Pull request merged**
