### PR TITLE
fix: avoid selecting the first element on autocomplete mode (#3262)

### LINKED ISSUE #3262: First option in autocomplete is always selected when pre-filling available options
### Overview of the problem

**Buefy** version: 0.9.5
**Vuejs** version: 2
**OS/Browser**: Independent

### Description

See https://codepen.io/emielmolenaar/pen/QWdpBJW .

First option in autocomplete is always selected when pre-filling available options. I use a tag input with the autocomplete feature and a pre-filled set of options to choose from. Since Buefy 0.9.5, the first option is always selected (even if you do not select any option form the autocomplete dropdown).

### Steps to reproduce

See https://codepen.io/emielmolenaar/pen/QWdpBJW . Try to remove the options, or to add no option at all.

### Expected behavior

When I don't click / select an option, the dropdown should just close and not append any option to the list.

### Actual behavior

The first option is always appended to the list.

I think this is caused by the change "Automatically select hovered option on blur for Autocomplete (thanks @fabiofdsantos)", or am I doing something wrong?

### PR DESCRIPTION
**Pull request by fabiofdsantos**
Fixes #3262

## Proposed Changes

- Remove `allowNew` dependency of `keep-first`

### CODE REVIEW

**Comment by fabiofdsantos** [comment]
@jtommy Should we add a `keep-first` property to TagInput instead of removing the `allowNew` dependency?

**Comment by Thaurin** [comment]
> @jtommy Should we add a `keep-first` property to TagInput instead of removing the `allowNew` dependency?

Yes, please! I lost this functionality with release v0.9.6 and it would be great to have it back.

**Comment by jtommy** [comment]
Ok, make a PR

**Comment by fabiofdsantos** [comment]
I opened a new PR: https://github.com/buefy/buefy/pull/3299

**Comment by Thaurin** [comment]
You're too fast for me, I was trying to do it myself. :) Thanks!

**Pull request merged**
