### PR TITLE
Add scrollable and max-height to b-dropdown

### PR DESCRIPTION
**Pull request by franciscoh017**
Fixes #

## Proposed Changes

- Added Boolean prop scrollable to enable overflow on .dropdown-content.
- Added String/Number prop max-height to define the max height of .dropdown-content.
- Added Examples and Api description for the proposed props.

### CODE REVIEW

**Comment by jtommy** [comment]
What happen if I set scrollable to true without max height ?

**Comment by jtommy** [comment]
I think we need `scrollable` prop and when `max-height` isn't undefined set the overflow to auto, what do you think ?

**Comment by franciscoh017** [comment]
Great I’ll check the conditions and remove some changes that sneaked in the commit that messed up the coverage.

**Comment by jtommy** [comment]
Yes thanks, my fault about branch :(

**Comment by franciscoh017** [comment]
Right now, the conditions are set like this:
If scrollable == true: overflow is set to auto, if not then i none.

If scrollable == true, and max-height is not undefined then change dropdown-content to whatever the user has set. Also, i’’ defaulting it to 200px (as the default max-height of the auto complete).

**Comment by jtommy** [comment]
@franciscoh017 Please revert `if (this.isActive && event.keyCode === 27) {`

**Comment by franciscoh017** [comment]
When reverting i'm getting this error running tests:

Summary of all failing tests
 FAIL  src/components/dropdown/Dropdown.spec.js
  ● BDropdown › close on escape

    expect(received).toBeFalsy()

    Received: true

      133 |         wrapper.vm.keyPress({})
      134 |         wrapper.vm.keyPress(event)
    > 135 |         expect(wrapper.vm.isActive).toBeFalsy()
          |                                     ^
      136 |
      137 |         wrapper.vm.isActive = true
      138 |         wrapper.setProps({canClose: ['click']})

      at Object.toBeFalsy (src/components/dropdown/Dropdown.spec.js:135:37)


Test Suites: 1 failed, 69 passed, 70 total
Tests:       1 failed, 449 passed, 450 total
Snapshots:   58 passed, 58 total
Time:        53.746s

Am i missing something?

**Comment by jtommy** [comment]
Thanks, I updated a snapshot and all it's ok

**Comment by franciscoh017** [comment]
Perfect. Thanks!

**Pull request merged**
