### PR TITLE
Fix extra spaces inside table :/

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**
Fixes #

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
So, can you merge it now without reading any docs?

@jtommy

**Comment by afwn90cj93201nixr2e1re** [comment]
Also if you don't wanna use preserveWhitespace ruless, you should remove add `"vue/mustache-interpolation-spacing": ["error", "never"]` to eslint rules.

**Comment by jtommy** [comment]
Are you going to replace all interpolations ?
What's your really need ?

**Comment by afwn90cj93201nixr2e1re** [comment]
Yes, im gonna replace all of this stuff, coz you don't wanna merge preserveWhitespace, so, with deleting this we can use whitespace option, which is not 

> deprecated in TS file

**Comment by jtommy** [comment]
I'll work on it in the future, but at the moment I don't want replace all

**Comment by afwn90cj93201nixr2e1re** [comment]
You in future can take too much time, i know it.

**Comment by afwn90cj93201nixr2e1re** [comment]
Can you answer does it make any sense to current behaviour?
Why we can't merge it right now?

**Comment by afwn90cj93201nixr2e1re** [comment]
Now we can use preserveWhitespace and for future just add whitespace: preserve and on vue update(buefy package.json) just start replacing some useless stuff like spaces.

**Comment by jtommy** [comment]
I'll update project structure in order to separate docs and core code.
Then I'll take a look about it

**Comment by afwn90cj93201nixr2e1re** [comment]
When? Can i help you? To make it faster.

**Comment by afwn90cj93201nixr2e1re** [comment]
Can you create new repo in this org, and name it buefy-next for example, or @buefy and merge all stuff to new(just create copy) and then we can start working on it.

**Pull request closed without merging**
