### PR TITLE
Adding draggable to table rows

### PR DESCRIPTION
**Pull request by suneab**
Allows user to set :draggable="true" (default false) to enable dragging of rows. 
No swapping of rows has been implemented, but instead emits dragstart, dragover and drop events, with a payload of the event, row and index
draggable0

### CODE REVIEW

**Comment by jtommy** [comment]
@suneab Great! 
Could you add a simple effect css on drag and drop elements ? For example like your GIF.

**Comment by suneab** [comment]
@jtommy I'm not sure what I'm supposed to change. I just added dropEffect prop. Let me know if i misunderstood. 
draggableevent1

**Comment by jtommy** [comment]
@suneab I meant only in the example and not a new prop.

**Comment by suneab** [comment]
Right, yanked it all out again and added it to the example.

**Comment by jtommy** [comment]
@suneab Thanks!

**Pull request merged**
