### PR TITLE
Add autocomplete's OpenOnFocus prop to tagInput

### PR DESCRIPTION
**Pull request by rkacenski**
Simple fix that should allow the dropdown to show on the auto complete for tagInput components

### CODE REVIEW

**Comment by williamabbott** [comment]
@adrlen Does that mean it didn't get fixed?

**Comment by adrlen** [comment]
@williamabbott Indeed, adding this prop wasn't useful since Autocomplete inside TagInput already inherits `$attrs`

I'm looking to fix your issue #1286 but no success yet since this bug doesn't occur on my local with latest buefy version.

**Comment by williamabbott** [comment]
@adrlen interesting. What's your setup - browser & platform?

**Comment by adrlen** [comment]
@williamabbott Chrome/MacOs but I can reproduce the bug outside of the buefy project, there must be something different

**Comment by williamabbott** [comment]
@adrlen you're right, must me an issue on my side doh. thanks for the help though.

**Comment by williamabbott** [comment]
Do you know where I could start debugging this?

giphy

**Pull request merged**
