### PR TITLE
Drag-n-drop on touch screens (#3916)

### LINKED ISSUE #3916: Does Table draggable drag-n-drop work on touch screens?
### Discussed in https://github.com/buefy/buefy/discussions/3623

<div type='discussions-op-text'>

<sup>Originally posted by **lownlazy** December 22, 2021</sup>
From what I can see it doesn't but I hope I am missing something. I am using Chrome on Android and using (for example) this site: https://codepen.io/yxngl/pen/oRzdQe  
With a desktop and mouse the rows turn purple when clicked and drag-n-drop as expected. 
In touch screens there seems to be no drag events fired at all, the table behaves as if 'draggable' is set to false. 

Is there some way to enable draggable on a touch screen?

Many thanks for your help with this and the excellent Buefy software.</div>

### PR DESCRIPTION
**Pull request by kikuomax**
Fixes
- fixes #3916

## Proposed Changes

- Let `BTable` emulate drag-n-drop on touch-enabled devices
    - `BTable` captures touch events: `touchstart`, `touchmove`, and `touchend`
    - `BTable` inserts an extra `<div>` element to superimpose the dragged contents on the screen, which turns visible only while table rows or columns are being dragged
- Add how to start dragging rows on touch devices to the documentation page of `BTable`

**Remarks**: users have to **double-tap and hold** on a row to start drag-n-drop of the row on touch-enabled devices. Otherwise users cannot do touch-scrolling on `BTable`.

### CODE REVIEW

**Comment by kikuomax** [comment]
Anyone can test the behavior here: https://deploy-preview-3941--buefy-org.netlify.app/documentation/table#draggable-rowscolumns

**Comment by kikuomax** [comment]
> Anyone can test the behavior here: https://deploy-preview-3941--buefy-org.netlify.app/documentation/table#draggable-rowscolumns (Table - Draggable rows/columns)

I have tested the behavior on
- iPad Air 5th gen.
- Pixel 3a (mobile mode)

**Comment by wesdevpro** [comment]
> > Anyone can test the behavior here: https://deploy-preview-3941--buefy-org.netlify.app/documentation/table#draggable-rowscolumns (Table - Draggable rows/columns)
> 
> 
> 
> I have tested the behavior on
> 
> - iPad Air 5th gen.
> 
> - Pixel 3a (mobile mode)

I did some testing on the iPhone 11 Pro with the latest safari update and I've that the drag part of this feature does somewhat work. However the item being dragged does not drop as seen in the pictures below. 
image
image
image

**Comment by kikuomax** [comment]
> I did some testing on the iPhone 11 Pro with the latest safari update and I've that the drag part of this feature does somewhat work. However, the item is being dragged but does not drop as seen in the pictures below.

@wesdevpro Good catch! The floating shapes in the mobile card mode did not resemble what they were displayed in the table (card list) at all. I think the latest commit better imitates the table contents.

**Comment by wesdevpro** [comment]
> > I did some testing on the iPhone 11 Pro with the latest safari update and I've that the drag part of this feature does somewhat work. However, the item is being dragged but does not drop as seen in the pictures below.
> 
> @wesdevpro Good catch! The floating shapes in the mobile card mode did not resemble what they were displayed in the table (card list) at all. I think the latest commit better imitates the table contents.

@kikuomax I am still having issues with what is displayed in the list after a drag-and-drop attempt. Was the Netlify link rebuilt from the latest commit on this PR?

**Comment by kikuomax** [comment]
> @kikuomax I am still having issues with what is displayed in the list after a drag-and-drop attempt. Was the Netlify link rebuilt from the latest commit on this PR?

@wesdevpro Could you share what you expect to see?

FYI, the attached video shows what I had expected and saw on the above Netlify preview on iPhone 15 Pro simulator.

https://github.com/buefy/buefy/assets/3257531/8685f6c4-6f34-4966-8741-7f126b4fca20

**Comment by wesdevpro** [comment]
> > @kikuomax I am still having issues with what is displayed in the list after a drag-and-drop attempt. Was the Netlify link rebuilt from the latest commit on this PR?
> 
> @wesdevpro Could you share what you expect to see?
> 
> FYI, the attached video shows what I had expected and saw on the above Netlify preview on iPhone 15 Pro simulator.
> 
>  DnD.on.iPhone.15.Pro.mp4

I was expecting to see the table

> t commit better imitates the table contents.

@kikuomax I was expecting the table to update when you let go of the table item. If you look at the date in the item you dragged in the video that item never moves. Was this expected?

**Comment by kikuomax** [comment]
> @kikuomax I was expecting the table to update when you let go of the table item. If you look at the date in the item you dragged in the video that item never moves. Was this expected?

@wesdevpro It was expected. The documentation page of `BTable` does not actually change the table items after drag&drop but only pops up a toast message:
https://github.com/buefy/buefy/blob/0f4115445f40a5a12d6a2f9daab2f59aed5faf28/docs/pages/components/table/examples/ExDraggableRows.vue#L77-L81

`BTable` neither changes the table items with drag&drop. It is "drop" handlers' responsibility. So nothing happens to the table items in the example.

**Comment by wesdevpro** [comment]
> > @kikuomax I was expecting the table to update when you let go of the table item. If you look at the date in the item you dragged in the video that item never moves. Was this expected?
> 
> @wesdevpro It was expected. The documentation page of `BTable` does not actually change the table items after drag&drop but only pops up a toast message:
> 
> https://github.com/buefy/buefy/blob/0f4115445f40a5a12d6a2f9daab2f59aed5faf28/docs/pages/components/table/examples/ExDraggableRows.vue#L77-L81
> 
> `BTable` neither changes the table items with drag&drop. It is "drop" handlers' responsibility. So nothing happens to the table items in the example whether it is running on mobile devices or not.

Thank you for the explination.

**Review by wesdevpro — APPROVED** [review]

**Pull request merged**
