### PR TITLE
Typescript button props definitions

### PR DESCRIPTION
**Pull request by CharlieBrownCharacter**
## Proposed Changes

- add typescript button props definitons

### CODE REVIEW

**Comment by CharlieBrownCharacter** [comment]
@jtommy I'm heavily using Buefy with typescript and have been adding a lot of typing definitions. With this in mind I think that the current structure will not be scalable. I was thinking of re-organizing the files in such structure:

```
- components
  - button.d.ts
  - carrousel.d.ts
  - ...
- helpers.d.ts
- index.d.ts
```

I know this comment is out of bound of this PR but I don't know how to reach you directly to ask such questions

**Comment by jtommy** [comment]
Ok about reorganization, thanks

**Comment by jtommy** [comment]
Looking your code I don't understand where you are defining button component. Am I missing anything ?

**Comment by CharlieBrownCharacter** [comment]
@jtommy I didn't switch the components to what we spoke about (divide by folders as we spoke about)

**Comment by jtommy** [comment]
Yes, but at the moment thee missing type error is not fixed

**Comment by CharlieBrownCharacter** [comment]
@jtommy what do you mean?

**Comment by jtommy** [comment]
Where is button component definition?

**Comment by CharlieBrownCharacter** [comment]
@jtommy over here: `types/components.d.ts`. You can check the interface defined `ButtonProps`

**Comment by jtommy** [comment]
But the component is Button and not ButtonProps

**Comment by CharlieBrownCharacter** [comment]
Usually I give the name props because this is not the type definition for the entire component but for the props. The definition for the entire component would involve something like `ComponentOptions<any, any, ButtonProps>`

**Comment by jtommy** [comment]
Ok, where is the component definition?

**Pull request merged**
