### PR TITLE
feat: publish `Buefy v0.9.26` to `npm`

### LINKED ISSUE #2621: Modal: Display close button in mobile version
### Overview of the problem

**Buefy** version: ^0.8.20
**OS/Browser**: Google Chrome 85.0.4173.2 (Official Build) dev (64-bit)

### Description
image

### Steps to reproduce

My custom component:
```html
<div class="modal-card" style="width: auto;">
    <section class="modal-card-body is-titleless">
        Content...
    </section>
</div>
```

Parent component:
```ts
this.$buefy.modal.open({
    parent: this,
    component: MyCustomComponent,
    hasModalCard: true,
    trapFocus: true,
})
```
Example in codepen:
https://codepen.io/fabiofdsantos/full/oNbWMPq

### Expected behavior

Display [x] button properly.

### Actual behavior

[x] is hidden in mobile version (e.g. 320x568).

### LINKED ISSUE #2681: Table: customSort does not work when sortMultiple is enabled
### Overview of the problem

**Buefy** version: [0.8.20]
**Vuejs** version: [2.6.11]
**OS/Browser**: Windows 10/Chrome 83.0.4103.116

### Description

`customSort` function is not called when `sortMultiple` is enabled on a Table.

### Steps to reproduce

1. Create a Table with `sortMultiple`
2. Create a column with a `customSort` function
3. Try to sort that column and see if the `customSort` function gets called

### Expected behavior

Table column should be sorted using the `customSort` function.

### Actual behavior

The column does not get sorting at all and the row order remains unchanged. No errors are reported on the console.

### LINKED ISSUE #2886: Table with sticky-header and sortable clips sort icon
### Overview of the problem

**Buefy** version: 0.9.3
**Vuejs** version: 2.6.11
**OS/Browser**: OSX, Chrome

### Description

For tables with sticky-headers and sortable rows, part of the sort icon gets clipped by the next column. This is because sticky-headers applies a white background to the `th`, which goes on top of the icon. 

### Steps to reproduce

https://codepen.io/abroekhof/pen/BaKPRwM

### Actual behavior
image

### Possible solutions

1. Apply the background color to the row instead of each cell individually
2. Increase the z value for the icon
3. Increase right padding in case of sortable and sticky-header

### LINKED ISSUE #3074: Tag with close in tag list produces unwanted offset
### Overview of the problem

**Buefy** version: "^0.9.3"
**Vuejs** version:  "^2.6.12",
**OS/Browser**: Firefox 83, Chromium 87

### Description
in a taglist, if a tag is "attached", it is not aligned with other tags

### Steps to reproduce
```
      <b-taglist>
        <b-tag v-for="(tag, key) in tags" :key="key" :type="'is-' + key">{{
          tag
        }}</b-tag>
        <b-tag
          type="is-primary"
          close-type="is-primary"
          closable
          attached
          >Offline
        </b-tag>
      </b-taglist>
```

### Expected behavior
tag should be aligned with others even with an attached close icon.
as it already works with the "closable" when not "attached"
image

### Actual behavior
Tags are not aligned

image
image

### LINKED ISSUE #3726: Horizontal scrollable table ignores column width
### Overview of the problem

**Buefy** version: [0.9.17]
**Vuejs** version: [2.6.14]
**OS/Browser**: Chrome 100.0.4896.75 

### Description

When applying `width` to a table column it is being ignored on tables that overflow.

### Steps to reproduce

https://codepen.io/donmb1/pen/ExoReaq?editors=1010
Please check the computed `columns()` and the column `first_name` and `last_name`

### Expected behavior

Width should apply just as with non scrollable tables

### Actual behavior

The table column with the applied width is not expanding

### LINKED ISSUE #3753: Tooltip Glitchy
**Buefy** version: 0.9.20
**Vuejs** version: 2.6.11
**OS/Browser**: Safari MacOS Monterey

### Description

When I add the prop **appendToBody** to tooltip component, to show it inside a modal, the behavior is glitchy

### Steps to reproduce

1. Put a tooltip inside a modal
2. Set appendToBody prop to true
3. Try on Safari

### Expected behavior
Normal like other tooltips instances

### LINKED ISSUE #3872: SVG icons too large in Safari
### Overview of the problem

**Buefy** version: 0.9.23
**Vuejs** version: 2.7.14
**OS/Browser**: MacOS/Safari

### Description

When using font awesome SVG icons, they are way too large in Safari.

### Steps to reproduce

(I'd love to share a CodePen snippet, but the template does not work for me)

#### 1. In a suitable folder, install vue-cli and create a new Vue 2 project:
```
$ npm install @vue/cli
$ vue create repro
```
Pick 2.x.x.

#### 2. Add the dependencies
In the `dependencies` section in `repro/package.json`
  1. Replace the Vue version 2.6.14 with 2.7.14 in 
  2. Add the following:
```
    "@fortawesome/fontawesome-svg-core": "^6.4.0",
    "@fortawesome/free-solid-svg-icons": "^6.4.0",
    "@fortawesome/vue-fontawesome": "2",
    "buefy": "^0.9.23"
```

Now run `npm install` in the repro folder.

#### 3. Add the code
Replace the template in `src/components/HelloWorld.vue` by
```
<template>
  <div class="hello">
    <b-notification type="is-danger" has-icon role="alert" :closable="false"><p>This is a notification.</p></b-notification>
    <b-button icon-pack="fas" icon-left="info-circle">Button</b-button>
  </div>
</template>
```

Replace the code in `main.js` by
```
import Vue from 'vue'

import Buefy from "buefy";
import 'buefy/dist/buefy.css'

import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import {
  faExclamationCircle,
  faInfoCircle,
} from "@fortawesome/free-solid-svg-icons";

import App from './App.vue'


library.add(
  faExclamationCircle,
  faInfoCircle
);

Vue.component("vue-fontawesome", FontAwesomeIcon);

Vue.use(Buefy, {
  defaultIconComponent: "vue-fontawesome",
  defaultIconPack: "fas",
});

new Vue({
  render: h => h(App),
}).$mount('#app')
```

#### 4. Run
```
$ npm run serve
```

### Expected behavior

In Chrome and Firefox the icons are properly sized:
image

### Actual behavior

In Safari, the icons are very big:
Screenshot 2023-08-07 at 14 35 00

### LINKED ISSUE #3887: Invalid type error for tags
### Overview of the problem

**Buefy** version: 0.9.23
**Vuejs** version: 2.6.14
**OS/Browser**: OSX / Chrome 

### Description

I wanted to try different tag types based on conditions. In this case i have a time table with bookable slots, reserved one and one selected item.

I used the following code to get this result:
` b-tag(:type="{ 'is-primary': !isBooked(day, slot), 'is-light': !isSelected(slot, day) }") [[ slot.start]] - [[ slot.end ]]` 

SCR-20230919-aej

But, even tho we see it working it is producing the following error:

SCR-20230919-ajl

### Steps to reproduce

1. User a tag item with an object for its type rather than strings

### Expected behavior

As objects already work, the above error should not be triggered.

### Actual behavior

I see errors popping up AND Buefy accepting the object and rendering the type correctly.

I tried to set this [CodePen template](https://codepen.io/service-paradis/pen/KKgJZOK) up, but it wasnt displaying Buefy CSS for me.
Anyway, this works for me as some test code:

`<b-field><b-tag :type="{'is-primary': true}">test</b-tag><b-field>`

And interestingly it is producing two error for this one tag item.

### LINKED ISSUE #3939: unnecessary component duplication in navbar-item
### Overview of the problem

**Buefy** version: [0.9.25]
**Vuejs** version: [2.7.15]
**OS/Browser**: Windows10/Vivaldi

### Description
It seems that Buefy creates two navbar-item element with the only difference is the `is-hidden-touch` or `is-hidden-desktop` classes

This cause an issue when getting tests to click the navbar-item as it duplicates the key

### Steps to reproduce
1 - create a navbar with an attribute on its navbar-item:
```
<b-navbar-item
		data-test-id="localeHe"
		@click="switchLanguage"
		>
		he
</b-navbar-item>
```

### Expected behavior

attribute exists only once in the DOM

### Actual behavior
There is a duplicate navbar-item that looks almost exactly the same

Look at the `data-test-id` attribute
image

### PR DESCRIPTION
**Pull request by wesdevpro**
## Proposed Changes
- Publish the following changes as `v0.9.26` to `npm`.

### New features

* Add `render-on-mount` prop to modal
* Add `startLoading` and `stopLoading` methods to dialog (thanks @zhanghengxin)
* Add drag-and-drop support to table for mobile devices

### Fixes

* Fix dropdown position when autocompleted and appended to body (thanks @francisfontoura)
* Fix b-button nativeType for tag 'input' (thanks @mistersaal)
* Fix #3887 Invalid type error for tags
* Fix #3872 SVG icons too large in Safari
* Fix #3753 and #3065 Tooltip Glitchy
* Fix #3726 Horizontal scrollable table ignores column width
* Fix #2886 and #3034 sort icons on Table overlapped next columns
* Fix #2621 Modal: Display close button in mobile version
* Fix #2681 Table: customSort does not work when sortMultiple is enabled
* Fix #3939 unnecessary component duplication in navbar-item
* Fix #3074 Tag with close in tag list produces unwanted offset

### CODE REVIEW

**Review by kikuomax — APPROVED** [review]
I know we are good to go!

**Comment by kikuomax** [comment]
@wesdevpro 
I will locally merge `dev` to `master`, and update `master`.

**Comment by miroslavgeorgiev** [comment]
What about Nuxt version - planning update there?

**Comment by wesdevpro** [comment]
> What about Nuxt version - planning update there?

Yes we can bump the version in the nuxt buefy project. However please see #3957

**Comment by wesdevpro** [comment]
> What about Nuxt version - planning update there?

See https://github.com/buefy/nuxt-buefy/pull/149

Let us know if you run into any bugs

**Pull request merged**
