### PR TITLE
Add the possibility to show the week number

### LINKED ISSUE #1349: Date picker week number [QUESTION]
### Description

Hy,

Is it possible to view the week numberson the datepicker of buefy?
For example I post this message on April 26 and we are the week 17 of the year 2019

I would like to be able to view the week numbers on the datepicker

Thank you in advance

### PR DESCRIPTION
**Pull request by quadra-diffusion**
Fixes #1349 

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by quadra-diffusion** [comment]
Hello, i don't know why Circle CI doesn't work. In my machine, the tests are ok

**Comment by jtommy** [comment]
I have to fix timeout

**Comment by quadra-diffusion** [comment]
@jtommy Thanks a lot  ! How can i do to rebuild ? the button is disabled

**Comment by jtommy** [comment]
Thanks!

**Pull request merged**
