### PR TITLE
Fix #1542  for Steps

### LINKED ISSUE #1542: Completed step item is not clickable on default
### Overview of the problem

**Buefy** version: [0.7.10]

### Description

The `clickable` API of step item says 

> Item can be used directly to navigate. If undefined, completed steps are clickable while the others are not.

But even if `clickable` is left unspecified, it will still be `false` not `undefined`. https://github.com/vuejs/vue/issues/8704

### Steps to reproduce

Any example in the doc page.

### Expected behavior

Completed step item is clickable.

### Actual behavior

Completed step item is disabled.

### PR DESCRIPTION
**Pull request by service-paradis**
Fixes #1542

## Proposed Changes

- Improve the default behavior for clickable steps
- This is a potential breaking change.
- Should be considered for 0.8.0

### CODE REVIEW

**Comment by jtommy** [comment]
Probably it's a breaking change but it a new component too.
By the way next version will contains some breaking

**Comment by afwn90cj93201nixr2e1re** [comment]
That's not a hood idea for change author paradigmas.

Why do you think this is the good idea to change complete to previos? What about if there some disabled steps and you gonna check with condition if a > b, nice, very good, keep going.

**Comment by service-paradis** [comment]
@afwn90cj93201nixr2e1re
I dont really understand what th problem is in your example.

It is only changing a little bit the default behavior for something we often see in Steps component. It is what most people expect from a Steps component. This behavior can be entirely customized anyway using the `clickable` prop on a step item.

This will also e merged in 0.8.0 which is a breaking release.

**Comment by afwn90cj93201nixr2e1re** [comment]
No that's not default way :/
I wanna set completed when i want, not when this is last item at all.

**Comment by service-paradis** [comment]
The prop `completed` was doing nothig before thir PR.
The only thing this PR is doing is to make a previous step clickable to be able to navigate back to it. This behavior can be customized using the `clickable` prop. So you can use it the way you want.

**Comment by afwn90cj93201nixr2e1re** [comment]
изображение

Oh, yes, nothing.

**Comment by service-paradis** [comment]
It was doing nothing because the default value was `false`. There was no way to set this value to `undefined`.
This condition was never met.

**Pull request merged**
