### PR TITLE
Improve tests for FieldBody.vue

### PR DESCRIPTION
**Pull request by afifsohaili**
Couldn't get `Field.vue`'s spec to 100% because the code coverage isn't telling me the correct lines my spec hasn't hit.

### CODE REVIEW

**Comment by jtommy** [comment]
@anteriovieira Could you take a look ?

**Comment by jtommy** [comment]
@afifsohaili Please split in two PRs. One for test and one for FieldBody, thanks.
About test what's the issue using eslint ?

**Comment by anteriovieira** [comment]
@afifsohaili follow the guidelines of @jtommy, doing this, it's okay.

**Comment by afifsohaili** [comment]
> About test what's the issue using eslint?
It's not for tests. It's a general improvement that I discovered I could do as I was working on the project.

Using `lint --fix` will go back to the `lint` script declared in `package.json`. So it will also pass the options and the directories. That means, on precommit it will run `eslint --ext .js,.vue src docs` instead of just `eslint --fix`.

**Comment by afifsohaili** [comment]
I'll resolve conflicts by end of tomorrow. Currently a bit preoccupied.

**Comment by jtommy** [comment]
@afifsohaili Thanks

**Pull request merged**
