### PR TITLE
Add paginationPosition prop to table component

### PR DESCRIPTION
**Pull request by service-paradis**
Ref: #717

Add the option to display the pagination at the bottom (default), top or both.

It also add a new slot `top-left` when the pagination is displayed at the top.

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
You know that level isn't responsive well?

**Comment by service-paradis** [comment]
I used the same layout for the top pagination than the bottom one.
The responsiveness improvements could be made in another PR.

**Comment by jtommy** [comment]
@service-paradis please fix conflicts so i'll merge it

**Comment by service-paradis** [comment]
@jtommy Done :)

**Comment by jtommy** [comment]
What did you do ? I have to revert your commit, please check it and open a new PR

**Comment by service-paradis** [comment]
Damn, So sorry for this! Dont know what happens.
I will create another clean PR.

**Pull request merged**
