### PR TITLE
<b-progress> component

### PR DESCRIPTION
**Pull request by MeikelLP**
For features request #953

**TODO**
* Coding
  * [x] Write basic component
  * [x] Value updates automatically
  * [x] Colors
  * [x] Sizes
  * [x] Shown values (text)
  * [x] Status icon
* Documentation
  * [x] Add to documentation page  
  * [x] Simple example
  * [x] Complex example
  * [x] API reference

### CODE REVIEW

**Comment by zhaojh329** [comment]
[Feature request] 
image

**Comment by MeikelLP** [comment]
@zhaojh329 How important do you think is verticality? 

I don't think I can simply make it "nice" as I am not a CSS expert (responsive and stuff). As long as Bulma does not officially support vertical progress bars I don't think it's worth doing this (at the moment).

Currently, there is no such feature request on Bulma's side. I'd highly recommend starting there first :)

At the moment this is all I could give you (and even I am not satisfied): 
skizze 35

**Comment by zhaojh329** [comment]
Thanks.

**Comment by service-paradis** [comment]
I would love to have a progress component added to Buefy.

Here some personal comment on this PR. 
- It would be cool to have an option to specify the text position. Personnaly, I'm using progress like this: https://jsfiddle.net/gtcewpq3/
- I would prefer to specify the icon name as a string instead of passing a function. I prefer to use computed value inside my own component.

**Comment by service-paradis** [comment]
@jtommy 
Out of curiosity, is this PR will be merged into Buefy?
I'm using a homemade progress component (that looks like https://jsfiddle.net/gtcewpq3/). Should I made a PR for it?

**Comment by jtommy** [comment]
I didn't review it, I took a quick look months ago and there was something to change.
If you want make a simple version I'll review it and close this one

**Comment by service-paradis** [comment]
Great, I will try to do it next week!

**Comment by MeikelLP** [comment]
Closing this because @service-paradis seems to be more active than me. Please use my code to your hearts content

**Comment by jtommy** [comment]
I'm sorry @MeikelLP btw thanks!

**Comment by focux** [comment]
It should be good if the new progress component is a wrapper of Bulma's progress bar.
ref: https://bulma.io/documentation/elements/progress/

**Pull request closed without merging**
