### PR TITLE
Fix: Problem with table headers and dates moving from 0.9.25 to 0.9.27 (#3971)

### LINKED ISSUE #3971: Problem with table headers and dates moving from 0.9.25 to 0.9.27
Hi there,
Due to a misconfiguration on my side, I had specified the buefy version starting with ^ so the app "upgraded" automatically, I found out that there is some change in the 0.9.27 version that breaks the UI without any error, log, trace or clue what's going on.
The symptoms I have sees so far are that table header search boxes and data pickers are broken.
For example:
0.9.25
imagen
0.9.27
imagen
0.9.25
imagen
0.9.27
imagen
This is just changing "buefy": "0.9.25", to "buefy": "0.9.27".
I can see there are some changes in the DOM in the headers, for example:
0.9.25
imagen
0.9.27
imagen

The table header itself is defined as follows:
```
            <b-table-column field="formattedCodi" label="Codi" width="8%" cell-class="alignRight" sortable searchable>
              <template #searchable="props">
                <b-input
                  v-model="props.filters[props.column.field]"
                  placeholder="autor..."
                  @change.native="changedFilter"
                />
              </template>
```
So maybe there are some incompatibilities or other libraries to upgrade that I'm not aware of, I did not see anything about having to upgrade anything else in the changelog.
Anybody has seen this also? Any clue on what might be happening?
Also, a warning for those of you using 0.9.2X and do not specify ONE version, you might run into the same issue so be careful 😄 

Cheers!
D.

**Buefy** version: 0.9.27
**Vuejs** version: 2.6.12
**AFAIK All OS/All browsers**:

### PR DESCRIPTION
**Pull request by kikuomax**
Fixes #
- fixes #3971

## Proposed Changes

- Lower `vue` and `vue-template-compiler` to v2.6.11. See https://github.com/buefy/buefy/issues/3971#issuecomment-1890475953
- Won't apply `width` style to `.th-wrap` elements in `Table` if the column width is given in percentage
  - `width` style of `<th>` is usually ignored but has effect if the value is given in percentage

### CODE REVIEW

**Review by wesdevpro — APPROVED** [review]

**Comment by mary-josephine-1** [comment]
Is this Fix related to the below problem?

image


```
     <b-table-column v-slot="props" field="desks" label="Desks" searchable sortable>
     </b-table-column>
          
     <b-table-column v-slot="props" field="action" label="Action" width="10%" centered>
     </b-table-column>

```

Removing `center` or `width="10%"` will fix the problem.

**Comment by wesdevpro** [comment]
> Is this Fix related to the below problem?
> 
> image
> 
> ```
>      <b-table-column v-slot="props" field="desks" label="Desks" searchable sortable>
>      </b-table-column>
>           
>      <b-table-column v-slot="props" field="action" label="Action" width="10%" centered>
>      </b-table-column>
> ```
> 
> Removing `center` or `width="10%"` will fix the problem.

I haven’t done any digging but it could be. Could you copy and paste your comment as an issue reference this one?

**Comment by wesdevpro** [comment]
> Could you copy and paste your comment as an issue reference this one?

You can ignore this @mary-josephine-1 



> > Is this Fix related to the below problem?
> > image
> > ```
> >      <b-table-column v-slot="props" field="desks" label="Desks" searchable sortable>
> >      </b-table-column>
> >           
> >      <b-table-column v-slot="props" field="action" label="Action" width="10%" centered>
> >      </b-table-column>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Removing `center` or `width="10%"` will fix the problem.
> 
> @mary-josephine-1 @wesdevpro Yes, this PR will fix the problem, and you will be able to specify `width="10%"`.

@kikuomax Ah so it will be fixed in the next release from this PR ✅

**Comment by mary-josephine-1** [comment]
Thanks for the update. When can we expect the next PR?

**Comment by wesdevpro** [comment]
> Thanks for the update. When can we expect the next PR?

Our next PR to release a new version is currently being blocked by #4000

**Pull request merged**
