### PR TITLE
feature : implementing tree shaking in buefy

### PR DESCRIPTION
**Pull request by nikugogoi**
trying to implement this feature for making this plugin more modular. introduced a new function that can be imported and takes an array of strings(names of module) as argument. this function can be used in installing the plugin to vue.
also made an edit to apply custom classes on the checkbox and radio. Eg. apply checkbox class to radio to make the radio buttons look like checkboxes

### CODE REVIEW

**Comment by nikugogoi** [comment]
hey @jtommy @rafaelpimpa @anteriovieira .... will this PR be a problem?

**Comment by nikugogoi** [comment]
@jtommy @rafaelpimpa @anteriovieira .... could you review this PR
I am having problems testing my build

**Comment by nikugogoi** [comment]
I could not run tests due to this issue #738

**Comment by jtommy** [comment]
@nikugogoi We prefer have not only one PR for different scopes.
Anyway we're writing part of Buefy build, then you could take a look and improve it if needed

**Pull request closed without merging**
