### PR TITLE
Allow disabling controls.

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**
Fixes #

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by jtommy** [comment]
@afwn90cj93201nixr2e1re It works only with keyboard, why do you need it?

**Comment by afwn90cj93201nixr2e1re** [comment]
Em, dont get it. I need it for that: #1990

I dont need buttons, can we add it?

**Comment by jtommy** [comment]
Please update the API docs before

**Comment by afwn90cj93201nixr2e1re** [comment]
Ok, wait one min. Thanks.

**Comment by afwn90cj93201nixr2e1re** [comment]
Done.

**Comment by jtommy** [comment]
Thanks

**Pull request merged**
