### PR TITLE
Jest localStorage

### PR DESCRIPTION
**Pull request by 14nrv**
When I launch the unit tests I got this:
"SecurityError: localStorage is not available for opaque origins"

Fixed with [testURL](https://github.com/jsdom/jsdom/issues/2304) in jest config

### CODE REVIEW

**Comment by jtommy** [comment]
@14nrv Where do you see the error ?

**Comment by 14nrv** [comment]
@jtommy It s in ALL the tests, in local
node_modules/jsdom/lib/jsdom/browser/Window.js

**Comment by jtommy** [comment]
@14nrv But I don't see it in console

**Comment by jtommy** [comment]
Fix https://github.com/buefy/buefy/commit/4e67557bbb94372df75ccc42380c6ea467037741

**Pull request closed without merging**
