### PR TITLE
Add a polyfill for the findIndex function

### PR DESCRIPTION
**Pull request by service-paradis**
## Proposed Changes

- Add a new helper function named findIndex
- Use the native function if available but revert to polyfill if not
- Steps pagination is now compatible with IE

### CODE REVIEW

**Comment by jtommy** [comment]
I didn't check findIndex but I prefer fix it using map + indexOf approach

**Comment by service-paradis** [comment]
No problem!
I made it this way since most of the browsers support it natively ([findIndex Compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex#Browser_compatibility)). I can change it using map/indexof instead.

**Comment by jtommy** [comment]
Yes I know but I don't want add other code at the moment

**Comment by service-paradis** [comment]
Yeah, I understand. Will fix the PR without the jelper function and having map/indexof to replace the actual findIndex.

**Comment by service-paradis** [comment]
@jtommy Fixed!

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy do you know anything 'bout js less memory using and performance or no?

**Comment by service-paradis** [comment]
@afwn90cj93201nixr2e1re 
What alternatives would you use to keep browsers compatibility?
The usage in steps would probably dont be affected that much by map performance. I dont think people use this cmponent with a lot of steps. Probably always below 10.

**Comment by jtommy** [comment]
@afwn90cj93201nixr2e1re I know it but I agree with @service-paradis

**Comment by afwn90cj93201nixr2e1re** [comment]
Just simple itteration i=0;i<array.length etc. Its faster 10 times and works on every browser.

Also polyfill that's suggested by service-paradise is better in this case.

Also we don't know how fast gc in ie10,11 etc.

**Pull request merged**
