### PR TITLE
<b-button> component!

### PR DESCRIPTION
**Pull request by bitkris-dev**
I've created a **b-button** component which includes a dynamic tag rendering (it can behave as a normal button, a submit button, a standard link and as a router-link based on **href** or **to** props; it even supports **target="_blank"** for external links), text and icon support (with their own **size**, **pack** and **position** related props and a **contents slot** for custom design).

There are several appliable states and styles based on the original Bulma docs: **is-outlined**, **is-inverted**, **is-rounded**, **is-hovered**, **is-focused**, **is-active**, **is-loading**

Colors (**btn** prop): **is-primary**, **is-info**, **is-link**, **is-success**, **is-warning**, **is-danger**

Sizes (**size** prop): **is-small**, **is-medium**, **is-large**

I've written the docs page, the API table and replaced the buttons in every page and components with the new **b-button** component. Everything works flawlessly.

It also emits a 'click' event when clicked, to support different manipulations.
You can read more about the component on the docs page itself.

## Why?

I find this component useful while iterating a loop of links (you can easily switch between a standard and router link) and to streamline many html tags into a single component for most of the common use-cases. I was surprised to discover there wasn't already a button component for Buefy, so I've created one.
**IT'S NOT ONLY SIMPLE HTML!** 😉
Hope you are not going to trash all these efforts!

### CODE REVIEW

**Comment by eunjae-lee** [comment]
I hope to use this soon :)

**Comment by jtommy** [comment]
@bitkris-dev We'll review as soon as possible

**Comment by gnsnnr** [comment]
Any news on this? Buttons are simple yet versatile components!

**Comment by Tzahile** [comment]
This PR is critical due to the fact that the current solution buefy suggests doesn't fit the button with size changes, ie:
```
<b-field>
  <b-input placeholder="Search..."
    type="search"
    icon="magnify"
    size="is-small">
  </b-input>
  <p class="control">
    <button class="button is-primary">Search</button>
  </p>
</b-field>
```
The input box size is changeable, but the button next to it isn't.

**Comment by jonbwalker** [comment]
@jtommy Any updates on this? I know it's a large PR and takes time. Would definitely like to use it.

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/c73c5daa97dd2c028ead59adb0c29ca389737b4a

**Pull request closed without merging**
