### PR TITLE
Fix incorrect props for rounded controls

### PR DESCRIPTION
**Pull request by service-paradis**
Replace `rounded` with `controls-rounded` in the documentation samples

### CODE REVIEW

**Comment by jtommy** [comment]
It's a breaking change, I'll think about it later

**Comment by jtommy** [comment]
It's about input, there is "Customization" for it

**Comment by service-paradis** [comment]
Hum, I'm not sure I understand your comment.

Tjhere was a typo in one of the example in the documentation for `b-numberinput`. If you look the first set of examples in https://buefy.org/documentation/numberinput, the rounded controls example is incorrect.

This Pull Request is only to fix the error in the documentation.

**Comment by jtommy** [comment]
It's ok, rounded prop applies "rounded" style to input while controls-rounded only to buttons

**Comment by service-paradis** [comment]
Ho, I'm sorry. There is 2 different properties. `rounded` and `controls-rounded`.
`rounded` property is missing at the bottom of the page:
image

**Comment by jtommy** [comment]
You're right and I'll add it, thanks

**Pull request closed without merging**
