### PR TITLE
Improve datepicker accessibility

### PR DESCRIPTION
**Pull request by imfaber**
Make datepicker accessible through keyboard only navigation (#1237 ).

**New behaviour**
- Tab into a datepicker field.
- Press `Enter` to open datepicker
- Use `Tab` + `Enter` to select a date or press `Esc` to close it

A new prop called `open-on-focus` has been added.
If true, the datepicker is open when the input field gets the focus (no need to press `Enter`).

### CODE REVIEW

**Comment by jtommy** [comment]
@imfaber Thanks! But first i would like check a common way using dropdown (if there is) because I'll be need to add it to timepicker too

**Comment by imfaber** [comment]
hey @jtommy 
No problem, if you think the solution for the datepicker is suitable for the timepicker I can work on it.
Let me know if I may help with anything 😃

**Comment by jtommy** [comment]
@imfaber I would apply a common solution to b-dropodown since datepicker, timepicker, autocomplete use it

**Comment by jtommy** [comment]
@imfaber Thanks

**Pull request merged**
