### PR TITLE
Some table customization

### PR DESCRIPTION
**Pull request by shelru**
percent's also must be allow

### CODE REVIEW

**Comment by jtommy** [comment]
@shelru It's a good idea but did you check to set a width without px o %?

**Comment by shelru** [comment]
o = or?
no.
If you can, just fix it, im newbie in js, xD. Add validator or smthng like dat.

**Comment by shelru** [comment]
So, and another question, where i can get' build files from 'ci/circleci' after tests? For testing.

**Comment by shelru** [comment]
Is that normal way?

**Comment by shelru** [comment]
xD, sorry for names.

**Comment by shelru** [comment]
Gabarage.   https://github.com/shelru/buefy/blob/dev/src/components/table/Table.vue#L51 also there must be v-if check's for `column.sortable`
image
image

@jtommy

**Pull request closed without merging**
