### PR TITLE
feat added Applitools and Cypress testing framework

### PR DESCRIPTION
**Pull request by sassypianist98**
**Changes**
This PR adds a suite of visual regression tests for Buefy docs using Applitools Eyes and Cypress. These tools allows for a seamless and lightweight testing of the documentation. When the tests are run, the Applitools SDK grabs DOM elements and takes snapshots of the style scripts. Then, Applitools launches Chrome and Firefox before rendering the selected elements (and any accompanying interaction with the UI) and taking screenshots of the specified visual components. The first time the tests are run, the snapshots will be saved as a baseline for comparison in future tests.

**Tests**
The test suite loads each page of the documentation and interacts with certain UI components to make sure they render correctly. The screenshots generated do not use pixel-by-pixel identification, but rather inspect as a human eye would, thus eliminating test failures caused by minuscule changes in pixelation. The current tests are already robust, but you can either cut them down or build upon them further. If you'd like to take a look, they are located in the cypress/integration folder.

To run the tests, you would need to create an account with Applitools, which will give you a unique ID needed to run the tests. You can receive your unique API key with a free account, but for OSS maintainers, more flexible, free unlimited accounts are also available. Once the account is created, you can use the command "export APPLITOOLS_API_KEY=value".

Please let me know if you'd like to take a further look into Applitools. I have created a testing framework using Jest, Jest Image Snapshot, Docker, AWS S3, and Jenkins before, and this is far more lightweight, efficient, and user-friendly. Thank you for your time in reviewing this PR.

For reference: https://applitools.com/docs/topics/overview/overview-visual-testing.html

### CODE REVIEW

**Comment by jtommy** [comment]
@sassypianist98 it's a great job!! I need time to check all but thanks a lot!!

**Comment by cmwhited** [comment]
@jtommy have you had a chance to look at this?

**Comment by jtommy** [comment]
@cmwhited sure! I'm waiting for Applitools free key

**Comment by cmwhited** [comment]
@jtommy just to clarify, did you apply and are waiting for them to respond?

**Comment by jtommy** [comment]
@cmwhited I've just received the email

**Comment by jtommy** [comment]
@sassypianist98 I runned it and it works well, thanks! But what do you think to remove screenshot and video folders and to add them in the .gitignore ?

**Comment by jtommy** [comment]
@sassypianist98 thanks, a last thing.. I runned the tests  and they seem to never end (all successfully btw)

**Comment by cmwhited** [comment]
@jtommy hmmm I am not running into the same issue. It run through all the tests successfully and doesn't close the window? Can you try it with `npx cypress run` instead of with `open`?

**Comment by jtommy** [comment]
@sassypianist98 can you check failed tests ?

**Comment by sassypianist98** [comment]
@jtommy We took at look at the failed tests, but I'm not sure if it's from this PR or not. What do you think?

**Pull request merged**
