### PR TITLE
Document & show use of horizontal forms

### PR DESCRIPTION
**Pull request by dlamblin**
## Proposed Changes
Updates documentation to show the correct use of horizontal because coming from bulma.io its not exactly obvious.
See my original confusion at https://github.com/buefy/buefy/issues/3309#issuecomment-894885101

### CODE REVIEW

**Comment by dlamblin** [comment]
@jtommy Please note that issue #3309 is not closed by this PR. I had added a comment onto its list of styling issues, only to find that *my* styling issues were due to a misapplication of bulma.io styles to the buefy components. The original issue calls out styling of the add-ons when the form is horizontal; which isn't covered in the examples update.

**Comment by mouadTaoussi** [comment]
Hello! The file named **exHorizontal** should end with .vue ext as well First letter should be Upper case just other files! Fix it as soon as possible Please!

**Comment by dlamblin** [comment]
@mouadTaoussi wouldn't you say that responsibility to fix it falls on the person who merged it?

**Comment by mouadTaoussi** [comment]
True I'm sorry, I decided to fix it and PR but I'm currently working on new component, I had no Time!

**Pull request merged**
