### PR TITLE
Fixes slash div warnings

### LINKED ISSUE #3669: Math Div Warnings in 0.9.15
### Overview of the problem

**Buefy** version: 0.9.15

### Description

Math div introduced in the newest version of Buefy which is deprecated. 

Screen Shot 2022-02-16 at 9 20 02 AM

### PR DESCRIPTION
**Pull request by SomethingNew71**
Signed-off-by: Cole Gentry <peapod2007@gmail.com>

Fixes #3669 

## Proposed Changes

- migrate away from / division

### CODE REVIEW

**Comment by jtommy** [comment]
I prefer to avoid use math dependencies as you can see in the other components

**Comment by SomethingNew71** [comment]
I just used the `sass-migrator` offered by dart to update them. The slash div stuff is deprecated so it throws downstream errors for anyone using newer versions of sass. Would you prefer it be `calc(12px / 4px);` as that is going to be supported according to the sass docs?

**Comment by jtommy** [comment]
As you can see https://github.com/buefy/buefy/pull/3372/files we avoid to introduce math package and we transformed as multiply

**Comment by SomethingNew71** [comment]
> As you can see https://github.com/buefy/buefy/pull/3372/files we avoid to introduce math package and we transformed as multiply

Updated! 😄

**Pull request merged**
