### PR TITLE
TagInput | add min width to input #613

### LINKED ISSUE #613: TagInput | Control field min-width
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.13]
**OS/Browser**: MacOS/Chrome64

### Description

When having multiple tags in TagInput, it can occur that the control field has a small width limiting what is visible.

### Steps to reproduce

Add multiple tags in tag input without having the control going back on the line

### Expected behavior

Have better vision on what is typed

### Actual behavior

screen shot 2018-02-16 at 17 45 29

Just setting a `min-width` should resolve this. PR ?

### PR DESCRIPTION
**Pull request by adrlen**
Fix #613

### CODE REVIEW

**Comment by adrlen** [comment]
Is it better to use `em` instead of `px` actually ?

**Comment by jtommy** [comment]
@adrlen Height is in `em`, so i think it's better use the same unit.

**Comment by adrlen** [comment]
fixed

**Comment by rafaelpimpa** [comment]
Isn't this already inherited from ``input`` class?

**Comment by adrlen** [comment]
It's set as `max-width: 100%;`

**Pull request merged**
