### PR TITLE
Datatable: support for custom row

### PR DESCRIPTION
**Pull request by carlobeltrame**
This includes just the first commit from #449, manually re-applied to the current repository state.

### CODE REVIEW

**Comment by EvanBarbour3** [comment]
@jtommy I've been looking for something like this.

What this pull request would do is allow people to provide their own custom row(s) in the detail slot which would be really useful. I've attached an image of what this could be used for if it was included. This may now be out of date

**Comment by EvanBarbour3** [comment]
@jtommy I've been looking for something like this.

What this pull request would do is allow people to provide their own custom row(s) in the detail slot which would be really useful. I've attached an example image of what this could be used for if it was included. 

This pull request may now be outdated, if you're interested in this feature I'd be happy to take a look.

I think passing the displayed columns into the slot would help, as people using the custom detail row would be able to manage the columns being displayed and hidden (currently handled in the available detail row via `:colspan="columnCount"`)

Screenshot 2019-04-17 at 10 11 17

**Comment by jtommy** [comment]
@EvanBarbour3 I don't understand very well the example in the PR, can you provide an example to make me change my mind ?

**Comment by jtommy** [comment]
In review #1336

**Pull request closed without merging**
