### PR TITLE
Emit event on Input icon click

### PR DESCRIPTION
**Pull request by service-paradis**
From a Discord comment

## Proposed Changes

- Add a new prop  `icon-clickable` that makes the icon clickable
- Emit `icon-click` event on click

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
@service-paradis are you sure? Coz i can't find is-disabled

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/buefy/buefy/search?q=pointer-events&type=Code

**Comment by afwn90cj93201nixr2e1re** [comment]
@click.native call also if condition is not complete.
And called on nextTick, so, there is a bug with promises or other stuff like that. I think we should just delete it, it's can't be implemented in rightWay.

**Comment by service-paradis** [comment]
image
https://github.com/jgthms/bulma/blob/9a28ea17876715d00d0a8a59b9fdabfee967e56b/sass/form/tools.sass#L176

**Comment by afwn90cj93201nixr2e1re** [comment]
Get you, but it's still not possible, it's not trully reactive.
You can test it, create button and ico.

Button should be async, for example with timeout 5 seconds.
Icon should have just handler for logging.

Click on button, and you also can click on ico, but event gonna be called after async function end up.
So, create variable loading: false, set it true on async function start and false on end, then try to repeat, it's also gonna be called.

**Comment by afwn90cj93201nixr2e1re** [comment]
Seem's like native click ignore any pointer rules.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://css-tricks.com/almanac/properties/p/pointer-events/
yeah, seem's like they aren't designed for that at all.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://bitsofco.de/theres-no-reason-to-use-pointer-events-for-html-elements/

**Comment by service-paradis** [comment]
Buttons are ont related to this PR... This PR add a click event on `b-input`...
Did you try this PR? It works... No emit when the icon is not clickable.

https://css-tricks.com/almanac/properties/p/pointer-events/ is explaining exactly the use made in this PR.

https://bitsofco.de/theres-no-reason-to-use-pointer-events-for-html-elements/
The exampe where he think it is not useful are not related to this PR. Also, it is a really opiniated article. No real arguments about having problem using it.

**Comment by afwn90cj93201nixr2e1re** [comment]
> Did you try this PR? It works... No emit when the icon is not clickable.

Did you tried what i wrote?
Bind some variable and check, it's gonna be clickable after condition is not true.

**Comment by afwn90cj93201nixr2e1re** [comment]
pointers are not solution for that, totally.

**Comment by service-paradis** [comment]
> Did you tried what i wrote?
You want me to try to put an icon inside a button.... This PR is about an icon within an input field. Totally not related....

It would not be the same solution if it was for a button... Pointers is already the solution for the mask password thing.

If you want to use something else. Create a new PR.

**Comment by afwn90cj93201nixr2e1re** [comment]
Spans arent designed for that, and there no reasons for that pr, that's not working as expected.

So, any pointers rules which arent related to **controls** should be removed from scss files.

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes span is not control.

**Comment by service-paradis** [comment]
Open a new issue in Bulma since pointers came from there.

Like I said, if you're not happy, create a new PR. Change the way toggling password is working right now too.

**Comment by afwn90cj93201nixr2e1re** [comment]
So, pr's like that then causing issues. That's not nice practice, ok, as @jtommy merged it, it's his headache.

**Pull request merged**
