### PR TITLE
Fix: Datetimepicker ignores expanded prop

### PR DESCRIPTION
**Pull request by cypressious**
## Proposed Changes

- Pass `expanded` prop to Datepicker

### CODE REVIEW

**Comment by jtommy** [comment]
Thanks

**Comment by frederic117** [comment]
Hello
When i use this and want to pass 
timepicker:{
                incrementMinutes:15,
                minTime:new Date(min),
                maxTime:new Date(max)
            },
it works for incrementMinutes but no for the minTime and maxTime (there are date object :))

Thanks for your help

**Comment by jtommy** [comment]
@frederic117 you have to use max-datetime and max-datetime to datetimepicker

**Comment by frederic117** [comment]
Hello 
thanks for your reply
But for exemple i want to use this to select a date between two dates (and min-datetime and max are  working fine) but the selectable time should be between 9 and 20:00 for exemple

**Comment by jtommy** [comment]
For each days?

**Comment by frederic117** [comment]
Yes

Le 12 nov. 2019 à 11:51, à 11:51, Walter Tommasi <notifications@github.com> a écrit:

**Comment by jtommy** [comment]
You'right, but please open an issue

**Pull request merged**
