### PR TITLE
Fix #1978

### LINKED ISSUE #1978: How override word spacing on autocomplete items.
изображение

```
<b-autocomplete>
            <div class="media words-overflow" slot-scope="props">....</div>
<b-autocomplete>
```

```css
.words-overflow {
    word-wrap: anywhere !important;
    word-break: break-all !important;
    white-space: unset !important;
}
```

Doesn't help. How we should disable white-spacing on parent **a** tag div?

Also heres no refs for this slot with a tag or other stuff.

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**
Fixes #1978

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by jtommy** [comment]
Aren't you able to add a custom style only adding a class to autocomplete component?

**Comment by afwn90cj93201nixr2e1re** [comment]
No, i tried, but it's overriding by other stuff, coz i can't access directly to dropdown item, nor inside slot overriding, nor class binding on component.

I don't wanna create too long rule for overriding it, coz sometime it's can be extended by buefy/bulma and my rules will no longer work.

**Comment by afwn90cj93201nixr2e1re** [comment]
Also i dont get why class bindings append to dropdown-menu instead autcomplete root div.

**Comment by afwn90cj93201nixr2e1re** [comment]
Hm, seems like this style(inside object) of class adding doesn't work. Should i create computed property instead this?

**Comment by afwn90cj93201nixr2e1re** [comment]
Caused by https://github.com/buefy/buefy/pull/927 and bulma

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy check this too https://github.com/buefy/buefy/issues/1946#issuecomment-553620048

**Comment by jtommy** [comment]
I really don't understand your need, you might customize the item using a slot or each items applying a root class to autocomplete

**Comment by afwn90cj93201nixr2e1re** [comment]
Show me how. You can't customize it now. Cox it's generating wrong rules.

**Comment by afwn90cj93201nixr2e1re** [comment]
Read #1946 and sass docs. for more info.

**Pull request closed without merging**
