### PR TITLE
Adds a key into detailed rows with prefix #423:

### PR DESCRIPTION
**Pull request by wanxe**
- Removes console.log on ExAsyncData component example.
- Change the data source of the ExDetailedRow to data_test.json

### CODE REVIEW

**Comment by jtommy** [comment]
@wanxe Is it still valid ? We decide to don't add `key` attribute to detail row, isn't it ?

**Comment by wanxe** [comment]
Too much time ago... let me check

**Comment by wanxe** [comment]
I think that you can add the key with prefixes if you want. Also I was changed the source data of the example and some stuff... So I know that now it can conflicts with the new changes, but with this PR seems better to me.

**Comment by jtommy** [comment]
Ok about example but at the moment no prefixes, thanks!

**Pull request closed without merging**
